### ISSUE TITLE
Update docker from 1.11.2 to 1.12.3, Failed to allocate and map port 5432-5432

### ISSUE THREAD

**Issue by zw963** [moby/moby#28372]
I install docker with, pull docker github repo, and checkout the correct git tag,
and compile it with docker.

when bundle is finished, I copy it to my system.

before update, it worked very well, after update, I could not start up any container correctly.

I even rm all files which exist in /var/lib/docker. (with BTRFS driver), still not work.

following is some error messages:

```sh
WARN[0585] Failed to allocate and map port 5432-5432: Error starting userland proxy:

Handler for POST /v1.24/containers/4c84b78b5a89e5702bd409a8905c8e16e24782f3677c597ae37e23552826be31/start returned error: driver failed programming external connectivity on endpoint ershou_web.pg_master.5432 (21870215edc282e4ff1ebd71d6625047933345dc555a70298a1874137341e076): Error starting userland proxy:  

```

Thanks.

**Comment by zw963** [comment]
I use BTRFS driver, and no 5432 is used before I start this container.

And, I run docker with `sudo docker args ...`

**Comment by zw963** [comment]
More context:
hello world is worked for me.

```sh
$  docker run ubuntu /bin/echo 'Hello world'
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
6bbedd9b76a4: Pull complete 
fc19d60a83f1: Pull complete 
de413bb911fd: Pull complete 
2879a7ad3144: Pull complete 
668604fde02e: Pull complete 
Digest: sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315
Status: Downloaded newer image for ubuntu:latest
Hello world
```

**Comment by zw963** [comment]
And revert to 1.11.2, all worked well now.

**Comment by aboutlo** [comment]
I got the same issue.

I fixed with two things: 
- destroy the containers & create them again
- restart of docker engine.

**Comment by thaJeztah** [comment]
Did you also build and update RunC, compile, and install the userland proxy, and compile and install, the correct version of containerd? Just replacing `dockerd` will not work.

Is there a reason you're trying to compile yourself, instead of installing the official packages?

**Comment by zw963** [comment]
@thaJeztah , I used Slackware, offical package is not offered for this release.
And, again, compile with docker self can Got the newest version. : )

When 1.11.2 is worked pretty well, If only replace all binary with 1.12.3, 
it found it not worked for me.

I notice some files is added. 

dockerd, I use it to start up daemon, it seem like work.
docker-proxy, I don't know what about this ...

Thanks.

**Comment by thaJeztah** [comment]
See this PR for the docker proxy; https://github.com/docker/docker/pull/23312

**Comment by zw963** [comment]
@thaJeztah , Still not got the point, sorry.

I try start dockerd with `--userland-proxy=false`, my container can start now
But I could not connect to port 5432 with local IP address: `127.0.0.1`.
Though `172.17.0.1` is worked for me.

If without this argument, my container is still not start.
I start dockerd with `-g /docker`. Following is dockerd start up log and
when I run `docker start ershou_web.pg_master.5432` err log.

```sh
DEBU[0000] docker group found. gid: 1003                
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] libcontainerd: new containerd process, pid: 18033 
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 227880         
INFO[0001] [graphdriver] using prior storage driver "btrfs" 
DEBU[0001] Using graph driver btrfs                     
DEBU[0001] Max Concurrent Downloads: 3                  
DEBU[0001] Max Concurrent Uploads: 5                    
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] Your kernel does not support swap memory limit. 
INFO[0001] Loading containers: start.                   
DEBU[0001] Loaded container 52c78a5dad08046b1fd77a4dc9fdcb52460eb37828731028d24c82a8c56b0003 
DEBU[0001] Option DefaultDriver: bridge                 
DEBU[0001] Option DefaultNetwork: bridge                
INFO[0001] Firewalld running: false                     
DEBU[0001] /usr/sbin/iptables, [--wait --version]       
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D OUTPUT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -F DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -X DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -F DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -X DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -N DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] Network (5cf0d64) restored                   
DEBU[0001] Allocating IPv4 pools for network bridge (5cf0d6438a7acef3b466570621ab1f78c47e00a41c9be9425cb8a46a9850423e) 
DEBU[0001] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway]) 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -D DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -o docker0 -j DOCKER] 
DEBU[0001] releasing IPv4 pools from network bridge (5cf0d6438a7acef3b466570621ab1f78c47e00a41c9be9425cb8a46a9850423e) 
DEBU[0001] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0001] ReleasePool(LocalDefault/172.17.0.0/16)      
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0001] Allocating IPv4 pools for network bridge (727612036bc3b77fcbdfed8d54e23e0bd1f31e8d315679e283276386a34b193e) 
DEBU[0001] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway]) 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -o docker0 -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /usr/sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION] 
INFO[0002] Loading containers: done.                    
INFO[0002] Daemon has completed initialization          
INFO[0002] Docker daemon                                 commit=6b644ec graphdriver=btrfs version=1.12.3
DEBU[0002] Registering routers                          
DEBU[0002] Registering HEAD, /containers/{name:.*}/archive 
DEBU[0002] Registering GET, /containers/json            
DEBU[0002] Registering GET, /containers/{name:.*}/export 
DEBU[0002] Registering GET, /containers/{name:.*}/changes 
DEBU[0002] Registering GET, /containers/{name:.*}/json  
DEBU[0002] Registering GET, /containers/{name:.*}/top   
DEBU[0002] Registering GET, /containers/{name:.*}/logs  
DEBU[0002] Registering GET, /containers/{name:.*}/stats 
DEBU[0002] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0002] Registering GET, /exec/{id:.*}/json          
DEBU[0002] Registering GET, /containers/{name:.*}/archive 
DEBU[0002] Registering POST, /containers/create         
DEBU[0002] Registering POST, /containers/{name:.*}/kill 
DEBU[0002] Registering POST, /containers/{name:.*}/pause 
DEBU[0002] Registering POST, /containers/{name:.*}/unpause 
DEBU[0002] Registering POST, /containers/{name:.*}/restart 
DEBU[0002] Registering POST, /containers/{name:.*}/start 
DEBU[0002] Registering POST, /containers/{name:.*}/stop 
DEBU[0002] Registering POST, /containers/{name:.*}/wait 
DEBU[0002] Registering POST, /containers/{name:.*}/resize 
DEBU[0002] Registering POST, /containers/{name:.*}/attach 
DEBU[0002] Registering POST, /containers/{name:.*}/copy 
DEBU[0002] Registering POST, /containers/{name:.*}/exec 
DEBU[0002] Registering POST, /exec/{name:.*}/start      
DEBU[0002] Registering POST, /exec/{name:.*}/resize     
DEBU[0002] Registering POST, /containers/{name:.*}/rename 
DEBU[0002] Registering POST, /containers/{name:.*}/update 
DEBU[0002] Registering PUT, /containers/{name:.*}/archive 
DEBU[0002] Registering DELETE, /containers/{name:.*}    
DEBU[0002] Registering GET, /images/json                
DEBU[0002] Registering GET, /images/search              
DEBU[0002] Registering GET, /images/get                 
DEBU[0002] Registering GET, /images/{name:.*}/get       
DEBU[0002] Registering GET, /images/{name:.*}/history   
DEBU[0002] Registering GET, /images/{name:.*}/json      
DEBU[0002] Registering POST, /commit                    
DEBU[0002] Registering POST, /images/load               
DEBU[0002] Registering POST, /images/create             
DEBU[0002] Registering POST, /images/{name:.*}/push     
DEBU[0002] Registering POST, /images/{name:.*}/tag      
DEBU[0002] Registering DELETE, /images/{name:.*}        
DEBU[0002] Registering OPTIONS, /{anyroute:.*}          
DEBU[0002] Registering GET, /_ping                      
DEBU[0002] Registering GET, /events                     
DEBU[0002] Registering GET, /info                       
DEBU[0002] Registering GET, /version                    
DEBU[0002] Registering POST, /auth                      
DEBU[0002] Registering GET, /volumes                    
DEBU[0002] Registering GET, /volumes/{name:.*}          
DEBU[0002] Registering POST, /volumes/create            
DEBU[0002] Registering DELETE, /volumes/{name:.*}       
DEBU[0002] Registering POST, /build                     
DEBU[0002] Registering POST, /swarm/init                
DEBU[0002] Registering POST, /swarm/join                
DEBU[0002] Registering POST, /swarm/leave               
DEBU[0002] Registering GET, /swarm                      
DEBU[0002] Registering POST, /swarm/update              
DEBU[0002] Registering GET, /services                   
DEBU[0002] Registering GET, /services/{id:.*}           
DEBU[0002] Registering POST, /services/create           
DEBU[0002] Registering POST, /services/{id:.*}/update   
DEBU[0002] Registering DELETE, /services/{id:.*}        
DEBU[0002] Registering GET, /nodes                      
DEBU[0002] Registering GET, /nodes/{id:.*}              
DEBU[0002] Registering DELETE, /nodes/{id:.*}           
DEBU[0002] Registering POST, /nodes/{id:.*}/update      
DEBU[0002] Registering GET, /tasks                      
DEBU[0002] Registering GET, /tasks/{id:.*}              
DEBU[0002] Registering GET, /networks                   
DEBU[0002] Registering GET, /networks/{id:.*}           
DEBU[0002] Registering POST, /networks/create           
DEBU[0002] Registering POST, /networks/{id:.*}/connect  
DEBU[0002] Registering POST, /networks/{id:.*}/disconnect 
DEBU[0002] Registering DELETE, /networks/{id:.*}        
INFO[0002] API listen on /var/run/docker.sock           
DEBU[0003] libcontainerd: containerd connection state change: READY 
DEBU[0024] Calling POST /v1.24/containers/52c78a5dad08/start 
DEBU[0024] container mounted via layerStore: /docker/btrfs/subvolumes/7df22ea6a6b36c6c60dd3fb1d01e2c0ac4b596b18a5f33c17ac6e33cd84df734 
DEBU[0024] Assigning addresses for endpoint ershou_web.pg_master.5432's interface on network bridge 
DEBU[0024] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0024] Assigning addresses for endpoint ershou_web.pg_master.5432's interface on network bridge 
DEBU[0024] Programming external connectivity on endpoint ershou_web.pg_master.5432 (7f4f09aeec84132443af6bcbd339dae92a65daee769b4cb9e752464390bf308b) 
DEBU[0024] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5432 -j DNAT --to-destination 172.17.0.2:5432 ! -i docker0] 
DEBU[0024] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 5432 -j ACCEPT] 
DEBU[0024] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 5432 -j MASQUERADE] 
DEBU[0024] /usr/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 5432 -j DNAT --to-destination 172.17.0.2:5432 ! -i docker0] 
DEBU[0024] /usr/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 5432 -j ACCEPT] 
DEBU[0024] /usr/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 5432 -j MASQUERADE] 
WARN[0024] Failed to allocate and map port 5432-5432: Error starting userland proxy:  
DEBU[0025] Releasing addresses for endpoint ershou_web.pg_master.5432's interface on network bridge 
DEBU[0025] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2) 
WARN[0025] failed to cleanup ipc mounts:
failed to umount /docker/containers/52c78a5dad08046b1fd77a4dc9fdcb52460eb37828731028d24c82a8c56b0003/shm: invalid argument 
ERRO[0025] Handler for POST /v1.24/containers/52c78a5dad08/start returned error: driver failed programming external connectivity on endpoint ershou_web.pg_master.5432 (7f4f09aeec84132443af6bcbd339dae92a65daee769b4cb9e752464390bf308b): Error starting userland proxy:  
```

**Comment by maxdebayser** [comment]
I have the same issue on RHEL 7.2 after updating to 1.12.3. But the --userland-proxy=false flag made it work for me again.

**Comment by zw963** [comment]
@maxdebayser , me too, I use docker with `--userland-proxy=false` as default arguments now.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
