### ISSUE TITLE
Swarm routing failures

### ISSUE THREAD

**Issue by ben-moore** [moby/moby#32079]
We are using swarm services with published ports to provide access to a number of services and web apps.  After a service update, we see intermittent connection failures (lack of response / timeouts).  The service being called does not appear to receive the request, it appears to be lost in the overlay network somehow. 

**Steps to reproduce the issue:**
1. Deploy an HTTP based service with a published port (using `docker service create`) with 2 or more replicas
2. Upgrade the service to a new version (`docker service update`)
3. Perform repeated requests to a machine using `curl http://machine:port`

**Describe the results you received:**
Worst case, every other request timed out / did not respond

**Describe the results you expected:**
Every request successfully routed to a running task for the service

**Additional information you deem important (e.g. issue happens only occasionally):**
Generally (but not always) resolved via a `docker service rm` / `docker service create` to reset the service, however this is not realistic in a production environment.

We are using labels to constrain specific services to certain nodes.  We are only routing requests to the servers meeting these criteria, although I know that we _could_ route to any server in the swarm if we wanted to.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
(from one of the swarm managers)
```
Containers: 14
 Running: 6
 Paused: 0
 Stopped: 8
Images: 16
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 212
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 1wspyg3dm7eik0pq1ut9iaotg
 Is Manager: true
 ClusterID: 0liuti0ieescusyzoftqhmj8t
 Managers: 3
 Nodes: 14
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.17.2.11
 Manager Addresses:
  0.0.0.0:2377
  172.17.2.11:2377
  172.17.2.12:2377
  172.17.2.13:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804 GiB
Name: stg-ne-mgr01
ID: YRT7:TRHX:5J33:Y2ZE:EBQT:4EHP:PWXS:V6RV:T6NU:CLKH:PYSM:F4PA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Azure VMs.  Host OS is Ubuntu 16.04 LTS

**Comment by ben-moore** [comment]
Saw this issue with 1.12 as well, but upgraded first before reporting to check it hadn't been fixed.

**Comment by mvdstam** [comment]
@ben-moore I think this is definitely related to #30321

**Comment by ben-moore** [comment]
@mvdstam certainly looks similar, although I don't see this as a temporary condition which that looked to be describing.  When a service gets into this state it doesn't recover, as if it permanently continues trying to route to a stopped task.

**Comment by Paxxi** [comment]
We also see this among other networking issues like the intermittent connection issues described in other tickets

**Comment by cpuguy83** [comment]
ping @aboch Seems this may still be an issue?

**Comment by joeljacobs** [comment]
We seem to be having the same problem. We're on the latest version. We run a curl command to the service (nginx) and it will work sometimes, then stop working for a long time. If we leave it alone, it will start working again for a while.

We are running the curl command with a "watch" command every 2 seconds.

Interestingly, we can reproduce this on many clients connecting to the service, but the  connection timeouts are host-specific. In other words, if we're being timed out on one client, another client can still connect. Sometimes we have just one client that can't connect, while all others can, and other times we have 1 or two that can't. We never have a situation when nobody can connect. 

This occurs even if we run the curl command on the hardware node where we're running the nginx service. This rules out the networking outside of the docker server. 

In all cases, if we wait a while, we can connect again. 

We can reproduce this on two swarms on different hardware in different locations and on different versions ( 17.05.0-ce and 1.12.5).

**Comment by ben-moore** [comment]
Yep agree with everything @joeljacobs says, the timeout issues we see are host-specific as well, also still an issue for us with 17.05.  The issue is _usually_ resolved by scaling a service to 0 and back again, or removing, re-adding the service.  I have seen one or two occasions where even this had no effect and the only way to resolve the issue was to restart the host that was not responding.

**Comment by hostingnuggets** [comment]
I can only confirm @ben-moore and @joeljacobs as I am experiencing exactly the same issue. At that time I was testing the traefik container and thought it would be related to traefik and not Docker so I posted an issue with them here https://github.com/containous/traefik/issues/1480

Seems that things are moving and hopefully this issue will be fixed with Docker 17.06.

**Comment by gzurbach** [comment]
Is there any workaround? I am comparing swarm and k8s to deploy our API right now. I'd love to use swarm but this issue is preventing us from moving forward. I am very new to docker so I'm not sure if swarm is even production ready. Any advice?

**Comment by cpuguy83** [comment]
Please test with the 17.06 rc, there are many improvements to these types of issues in networking and service discovery.

**Comment by captnbp** [comment]
Hi, I also have the same issue starting from 1.13 to 17.06 with published services. We have the problem with Ubuntu 14.04 and 16.04.

The only way for me to solve the issue is to scale back to 1. Scaling above 1 makes about half the requests timeout. and seems to concern only some nodes, not the same every time. 

So all requests concerning the node which started the first instance of the service seems to work, all other nodes for additional instances fails.

FYI in front of my Swarm cluster, I have an Azure LB which balances the incoming requests to my 3 nodes. With scale=1, no problem, scale>1 problems.

This is really impacting us, we can't scale...

**Comment by captnbp** [comment]
Hi, I also have the same issue starting from 1.13 to 17.06 with published services. We have the problem with Ubuntu 14.04 and 16.04.

Sometimes, scaling back to 1 fix the issue.

FYI in front of my Swarm cluster, I have an Azure LB which balances the incoming requests to my 3 nodes. 

This is really impacting us, we can't scale...

**Comment by kreeser00** [comment]
We are also facing same issue starting from 1.13 to 17.06 on Ubuntu 16.04.  In front of our cluster we have an Azure Application Gateway balancing requests to 3 worker nodes.  The routing failures appear as timeouts to the AG and ultimately result in 502 Bad Gateway response to the client.

The options we are considering are to use Docker without Swarm mode, use Swarm mode but only deploy 1 container of each service, or move to Kubernetes or Mesos.

**Comment by ben-moore** [comment]
Yep, I'm still seeing this issue on 17.06 as well.  Can someone from the Docker team feedback on this, as it definitely doesn't seem to be the same issue that was linked when I reported it.

**Comment by hostingnuggets** [comment]
Same for us, nothing changed while migrating from 17.03 to 17.06.

**Comment by diegito** [comment]
Same problem happening to us. We hit timeouts when querying services inside docker swarm. Restarting the affected services seem to fix the problem.

**Comment by mvdstam** [comment]
There seems to be a relevant fix [here](https://github.com/docker/libnetwork/pull/1824) waiting to be merged.

**Comment by Yablargo** [comment]
Running into the same issue here with 17.03 windows server worker and a 17.06 running ubuntu server 16.04. Need to get this working within the next 5 business days or I am hosed

**Comment by diegito** [comment]
The workaround I am trying for now is to pull out of Swarm the service that needs to be reached from an external source and have it running as standalone container. Obviously you lose the benefits of Swarm but at least it's running fine.

**Comment by cecchisandrone** [comment]
I'm facing the same issue, tried to remove the stack and deploy it again but no way. What is really strange is that if I put a very high request timeout on the client the response arrives after around 15 min sistematically.

**Comment by diegito** [comment]
I have the network routing failures at any time, not only on service update. Also after restarting a service the issue lingers.  I fixed it with what I mentioned before but... what's the point of having a Swarm if you can't use its features?

@ben-moore maybe we can change the title of the issue to simply "Swarm routing failures"?

It's a really big issue actually... I'm surprised there is no hotfix or any update from the docker team on this. Or am I wrong?

**Comment by fcrisciani** [comment]
I agree with @mvdstam this looks like a dup of https://github.com/moby/moby/issues/30321

**Comment by ben-moore** [comment]
@diegito I've updated the title.  I'm surprised that we haven't seen a fix for this too though, it's an issue we're battling with on a fairly regular basis at the moment.

**Comment by diegito** [comment]
@fcrisciani Thanks for your input. Issue #30321 seems to belong to 17.06 version milestone, but it seems we are able to reproduce this issue also on the latest (17.06) version. But I actually don't know how milestones work for this project 😄 

#30321 seems related to rolling updates, while the issue here is having connection refused responses from time to time when trying to connect to the swarm network, regardless of an update. Maybe related but not the same?

**Comment by fcrisciani** [comment]
@diegito the fix just miss the 17.06 train but is still a valid one.
Last week I found another issue on overlay that is track here: https://github.com/docker/libnetwork/issues/1934 maybe you can correlate and see if that is matching the signature that you have. The connection failure can last up to 5 min if the container does not send traffic out

**Comment by diegito** [comment]
Thanks @fcrisciani. I don't seem to relate that issue. What I see seem to happen even on a new instance that has never been started before. 
The pattern I see is rather random. If I have **n** instances of a container inside Swarm and try to contact the service port from outside the Swarm, I _sometimes_ get a request timeout. There's no consistency in what happens. Also for containers that have a single instance it happens the same: they are unreachable/timeout _at times_.
We tried restarting them, or also restarting the docker daemon but it does not seem to help. External traffic incurs in the same issue over and over.

Let me know if I can provide you with any other detail that can help you digging in this issue, or anything that you might want me to test on my end.

**Comment by fcrisciani** [comment]
@diegito did you try to investigate around resource limits? like file descriptors limit, socket reuses etc.? As far as I know I did not see other users or customers being affected by something like what you are describing

**Comment by diegito** [comment]
Inside `dmesg` I could not see anything abnormal besides one message that seem not to be a concern though:
`22592778.495781] aufs au_opts_verify:1597:dockerd[30266]: dirperm1 breaks the protection by the permission bits on the lower branch`.
Our swarm spawns over 3 machines with 3 managers and there were resources available in them.
We also moved (using swarm filters and tags) the external-facing services (services with ports exposed) in a machine with very low load, but the result was the same: seldom timeouts.
Number of requests hitting the server was not that high either and files descriptors were not a as far as I could see.
These are some sample logs we collected from an nginx instance in front of the cluster. 192.168.51.* are our machines.

```
2017/07/28 06:37:37 [error] 22380#22380: *18939 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 06:38:37 [error] 22380#22380: *18939 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 06:39:37 [error] 22380#22380: *18939 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 06:45:50 [error] 22381#22381: *19002 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 06:47:57 [error] 22381#22381: *19036 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard"
2017/07/28 06:59:58 [error] 22384#22384: *19095 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard"
2017/07/28 07:00:58 [error] 22384#22384: *19095 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 07:01:58 [error] 22384#22384: *19095 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 07:30:07 [error] 22378#22378: *19263 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 07:31:07 [error] 22378#22378: *19263 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 07:32:07 [error] 22378#22378: *19263 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:04:09 [error] 22381#22381: *19730 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:05:09 [error] 22381#22381: *19730 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:06:09 [error] 22381#22381: *19730 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:11:10 [error] 22383#22383: *19780 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:12:10 [error] 22383#22383: *19780 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:13:10 [error] 22383#22383: *19780 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:24:32 [error] 22383#22383: *19979 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:25:32 [error] 22383#22383: *19979 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:26:32 [error] 22383#22383: *19979 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:31:09 [error] 22388#22388: *20073 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:32:09 [error] 22388#22388: *20073 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:33:09 [error] 22388#22388: *20073 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:41:21 [error] 22389#22389: *20275 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:42:21 [error] 22389#22389: *20275 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 08:43:21 [error] 22389#22389: *20275 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 09:22:56 [crit] 22385#22385: *20711 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:ssl3_read_bytes:ccs received early) while SSL handshaking, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:443
2017/07/28 09:22:56 [crit] 22385#22385: *20712 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:ssl3_read_bytes:ccs received early) while SSL handshaking, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:443
2017/07/28 10:08:00 [error] 22389#22389: *21109 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.108:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 10:09:00 [error] 22389#22389: *21109 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.107:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
2017/07/28 10:10:00 [error] 22389#22389: *21109 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: test.domain.com, request: "DELETE /testurl HTTP/1.1", upstream: "http://192.168.51.109:7500/testurl", host: "test.domain.com", referrer: "https://test.domain.com/dashboard/"
```

**Comment by michalm86** [comment]
Still experiencing timeouts on 17.09

**Comment by diegito** [comment]
Sorry, forgot to provide update here. A month ago we tried again with the newest version of Docker 17.06 and the timeout issues we were experiencing were gone. We brought back all our services in production inside swarm and we haven't had a timeout since (the only timeouts we experience are when we release rolling updates, but that is not really a big concern). We will update soon to the newer Docker version and keep monitoring it. 
But for now upgrading to 17.06 seemed to solve the issue for some reason.

**Comment by robvelor** [comment]
@diegito We have tested `17.06.2-ce` and we are still facing timeout issues as well, pretty frustrating. Docker swarm is basically unusable for production. We have been testing it on and off since swarm mode was introduced and the issues always comes back intermittently, but it doesn't take long for it to happen.

**Comment by MoimHossain** [comment]
I have been struggling almost similar issues. Here's my configuration:
6 Nodes Swarm Mode cluster running on Azure (3 managers, 3 workers).

I have defined an overlay network for all my services, called '_mynet_'.

I have nginx service (a service with 3 tasks/replicas) running on master nodes only (with label constraints) and published port 80. The nginx service is acting as reverse proxy (layer 7 router) that has following configs:

```
http {  
  server {
    listen       80;

    location /api/ {
      proxy_pass       http://my-api:80/;
      proxy_http_version 1.1;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection keep-alive;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }  
}
```
The service created like:
```
docker service create --with-registry-auth --replicas 3 --name rproxy -p 80:80 --network=mynet --detach --constraint 'node.role==manager' some\myproxy:v1
```
Now, my API app is running as a service too, pretty much like:
```
docker service create --with-registry-auth --replicas 1 --name my-api --network=mynet  --constraint 'node.role==worker' some/image:v1
```

This was working for quite a while, I could hit the manager nodes from ourside (via a Azure Load balancer) like

http://loadbalancer.address.com/api/health

However, after a while, we started getting 502 gateway error while pushed a new version of the API image. 
To troubleshoot, I have ssh-éd into the nginx containers and saw that I can't **curl** url like, http://my-api:80/

It seems that docker DNS is not resolving service names to IP. The containers look fine though (when I do docker service ls, logs, ps, inspect etc.)

Docker version I have used:

```
:~$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I think it's a hard to reproduce bug, because often I scale the service (api app) down to 0 and wait a min and scale it back, and things starts working. Which makes me doubt it's a bug into the docker service name resolution process.

Could anybody from Docker team please shed a bit light here? As I have found plenty of people raising similar issues on Swarm, feel less confident running swarm on production. If this issue doesn't get addressed we might need to switch to K8s for production loads.

**Comment by ben-moore** [comment]
Would definitely be good to get some more feedback on this issue, it has been outstanding for nearly a year and we still see problems, it's got to the point where we are considering if we should move away from Swarm to de-risk this causing a production outage.

**Comment by fcrisciani** [comment]
A lot of people running 17.12-ce are reporting better stable behavior, my suggestion is to move to 17.12 and see how it goes

**Comment by diegito** [comment]
Just to give some more input here:
- On our end, things seemed to have stabilized with v17.06
- We tried to upgrade to v17.09 but the timeouts came back so we did not move forward.
- I'll test with v17.12 and post here if anything new happens

**Comment by diegito** [comment]
Alright, sorry for getting back so late. After I wrote last, we ran 2 weeks of testing our 5 node setup  of our staging environment (3M 2W). We added our services, used tools like AB and Siege to load the network with requests. We did not see any problem so we decided to move to prod. Now the system it's been running for over 2 months without that same issue repeating again.

We upgraded also to v17.12 and everything went smoothly.
We are testing docker v18.03 on staging now, but everything seems to be fine so far. 

I can say on our end this issue has been solved.

**Comment by fcrisciani** [comment]
@diegito ok thanks, I will ask to @thaJeztah to close this one for now, please follow up if you see the problem again on following releases

**Comment by thaJeztah** [comment]
Closing, per the discussion above, thanks!

**Comment by robvelor** [comment]
I tested this with 17.12.1 and we are still experiencing timeout issues. FYI I tried vkozlovski suggestion here: https://github.com/moby/moby/issues/32738 and the timeout issue seemed to take longer to happen (from a few minutes to days).

I will try with the latest and see.

**Comment by fcrisciani** [comment]
@robvelor I commented on the issue that you are mentioning, conntrack has a timeout of 15min for not active connection. This means that if there is no packets on the connection for that time, the connection is purged from conntrack and has to be established from scratch. Solution: enable TCP keepalive on the socket

**Comment by ushuz** [comment]
Seconding @robvelor, we are also experiencing timeout issues on 17.12.1. 3M 2W setup, the standalone nginxs in front of 2 worker node receive seldom 504 from time to time. Before migrating to swarm, the service was running inside standalone containers, and hardly ever return 504.

<img src="https://user-images.githubusercontent.com/1430856/38970688-777829ae-43c9-11e8-8d70-f68197cc5550.png" width=400>

I'll try adjusting keepalive settings and `dnsrr`.

**Comment by robvelor** [comment]
@fcrisciani Is this being tracked somewhere, it seems there are quite a few threads regarding timeout issues with swarm. Where do we need to enable the keep alive?

**Comment by fcrisciani** [comment]
@robvelor checkout this: https://success.docker.com/article/ipvs-connection-timeout-issue

**Comment by robvelor** [comment]
@fcrisciani Thank you, went back to vip mode after changing the keep alive and that seems to have done the trick. This is with `17.12.1`. @ushuz You should try this out.

**Comment by ushuz** [comment]
@robvelor No luck for me. I still got 504 after setting `net.ipv4.tcp_keepalive_time = 600`. Maybe there's something wrong with my application? Or maybe it's another bug / misconfiguration? I don't know. Now I run a level-4 lb service myself in global mode and application in dnsrr mode to bypass swarm's lb as a workaround. It's really frustrating.

**Comment by fcrisciani** [comment]
@ushuz just the kernel config is not enough, you need to enable the keepalive on the application socket

**Comment by ushuz** [comment]
@fcrisciani I'm running a gunicorn backend with gevent worker. It seem that gunicorn doesn't support TCP level keepalive. Any other options?

**Comment by fcrisciani** [comment]
@ushuz not familiar with the framework, but an hacky way is to have an application keepalive, you just need to use the connection before the 15min deadline to keep the entry fresh in conntrack

**Comment by ushuz** [comment]
@fcrisciani After digging deeper into this, my problem seems different from connections idle for too long. Our setup actually does not use long connection at all, instead, connection get closed after each request and enter TIME_WAIT state. So no idle connections but a bunch of short connections in my case, while alike symptom. I'm now testing long connections and hoping for the best.

**Comment by kreeser00** [comment]
@ushuz How did you set TCP level keepalive for your containers?  Or did you set it on each host?

**Comment by hostingnuggets** [comment]
I upgraded to 18.03.1-ce with the hope that in the mean time things got better but unfortunately I still get timeouts when doing rolling updates in my docker swarm services.  

I have a simple web app running on two different worker nodes (replica count 2) and an nginx 1.13 load balancer on a separate server in front configured to forward requests to my two docker swarm nodes. The nginx upstream is configured as such:

```
upstream myapp {
	least_conn;
	keepalive 32;
	server 192.168.0.11:10003 max_fails=0 fail_timeout=0;
	server 192.168.0.12:10003 max_fails=0 fail_timeout=0;
}
```

With a simple while loop and curlIa do an HTTP GET every second:
`while [ true ]; do curl http://myapp/hostname.json; sleep 1; done`

Then I start a rolling update and I will see twice a timeout (502 bad gateway returned by the nginx load balancer) for each time one second. I suspect that if I had 3 replicas I would see 3 timeouts.

Did anyone manage to get rid of these timeout with such as similar setup like mine? or is there maybe a workaround which I could implement on the load balancer?

**Comment by ushuz** [comment]
@kreeser00 Set on each host. See above link: https://success.docker.com/article/ipvs-connection-timeout-issue

---

@hostingnuggets Try increasing `max_fails` and `fail_timeout`, and make sure `proxy_next_upstream` is set correctly. Nginx should retry other upstream servers before giving up and return 502. If that didn't work out, maybe try `order: start-first` in update config.

**Comment by BretFisher** [comment]
I assume your replicas in this test have proper healthchecks so the VIP doesn't send connections to containers before they are ready.

What happens if you do this test without the nginx in front of swarm?

What happens if you do this test with `endpoint-mode: dnsrr` rather then default `vip`?

**Comment by hostingnuggets** [comment]
@BretFisher I do not have any health command defined for my simple test web app. Is this necessary for rolling updates to work? if yes would something like `--health-cmd "curl http://localhost:3000/"` be enough?

I tried running curl against my two worker nodes directly at the same time instead of the nginx load balancer and the same happens: for both worker nodes I get two timeouts `curl: (7) Failed to connect to 192.168.0.<NODE_IP> port 10003: Connection refused`.

Regarding switching my `endpoint-mode` from `vip` to `dnsrr` it looks like I can't do that if I am using the default swarm ingress overlay network, as I get the following error:
```
msg="Error updating service my8nk1mw7q0tm8k97to54tsj7: rpc error: code = InvalidArgument desc = EndpointSpec: port published with ingress mode can't be used with dnsrr mode"
```
Does this mean I need to create my own overlay network in order to use the dnsrr mode?

**Comment by fcrisciani** [comment]
@hostingnuggets to have no loss on rolling upgrade you need the heath check specified so that the container will be added to the load balancer once the health check passes, plus you will need a graceful shutdown period that will allow the container to not receive any new connection but to handle the one in flight.
This issue https://github.com/moby/moby/issues/30321 explains what you are seeing and this is the PR that takes care of it: https://github.com/docker/libnetwork/pull/2112

**Comment by hostingnuggets** [comment]
@fcrisciani thank you so much, that was it, I added a health cmd check to my service and I can do rolling updates without any interruptions of service. I will also have to test upscaling/downscaling but at least the restart of the service as it is works.

I can't recall having seen any mention in the official documentation that having a service health cmd check is a per-requisite in order to to have zero-loss rolling updates so I think the documentation might need some adapting to make it clearer.

**Comment by thaJeztah** [comment]
I added a "global" issue for adding more documentation around health checks here; https://github.com/docker/docker.github.io/issues/3282, perhaps you could add this use as a comment there

**Comment by fcrisciani** [comment]
@hostingnuggets great to hear that solved for you. 
The healthcheck is not needed if the container as it start running is ready to process requests. In that case you should not see any issue. If instead the process can require some time before being able to process operations then adding the healthcheck guarantees that the container is added to the load balancer once ready to accept new requests

**Comment by ushuz** [comment]
@kreeser00 Application timeout was set to 900. Make sure that TCP keep-alive was indeed enabled on both side. The original framework I used doesn't actually support TCP keep-alive, although it provides some parameters named "timeout" and "keepalive". I had to switch to another one with TCP keep-alive support to make it work.

Just FYI, another problem that have once caused timeout for me was MTU of overlay networks. Default MTU 1500 results in dramatic cross-node network performance degradation in my environment. After lowering MTU to 1454, the problem was gone.

**Comment by hostingnuggets** [comment]
@fcrisciani thank you for your additional remarks regarding the health checks. I am also glad to hear that some improvements in the health checks documentation is being doing. 

A last comment would be that I can hardly think of any service running in a docker container which does not require some time (speaking here in terms of 1-5 seconds) to startup and be ready especially for webapps. In my case it is a simple rails app which is ready within 1-2 seconds max but still requires a health check. So my impression here is that most of the time you would need to add a health check to your service.
