### ISSUE TITLE
Docker stack deploy support is limited to networks with scope=swarm

### ISSUE THREAD

**Issue by rreinurm** [moby/moby#32957]
**Description**
Using simple command in Docker Swarm-mode cluster `docker stack deploy -c docker-compose.yml example` it is not possible to deploy services which use external network with scope local defined. If I try to do it I get error message `network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"`

However using `docker service create ...` its possible to attach locally scoped networks. I understand that docker stack deploy command was implemented using best practices in mind, but currently users are limited to swarm networks only like overlay. In previous docker-compose it was possible to use key `network_mode:`, but its ignored now. Additionally it's not possible to attach to networks with Macvlan driver which also creates network with scope local.

In general I would like to remove this limitation that to connect to external network in docker-compose file the network has to be compliant with scope "swarm"

**Steps to reproduce the issue:**
1. Create docker-compose.yml file with content:
```
version: '3.2'
services:
  kitekat:
    image: kitematic/hello-world-nginx
    ports:
      - target: 80
        published: 8000
        mode: host
        protocol: tcp
networks:
  default:
    external:
      name: bridge
````
2. Try to execute command in Docker Swarm-mode cluster`docker stack deploy -c docker-compose.yml example`

**Describe the results you received:**
You get error `network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"`

**Describe the results you expected:**
It should create new Docker service with containers attached to bridge network

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 21
 Running: 7
 Paused: 0
 Stopped: 14
Images: 266
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ktgk0r8hudb0trs0nv4illjcu
 Is Manager: true
 ClusterID: nwhcro6doed2lwfgc31geih5l
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: MB44:MLUC:WCNE:5SZI:4OQO:Z6AH:SKVP:NGR2:Q3E5:WMGN:E536:YEMX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 73
 Goroutines: 207
 System Time: 2017-05-02T08:37:12.099504872Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Labels:
 partition=default
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Comment by rreinurm** [comment]
Just for extra infromation, if I use command `docker service create -p 'mode=host,target=80' kitematic/hello-world-nginx` then container is attached to bridge network by default without any complaints.
Snippet from docker inspect
```
"Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "cf8fbb5375343af1b52ae11902c537000c86cba2502156bdced22652a75ba74f",
                    "EndpointID": "a41642bf263058e82b788634adc71d991aca46018815756c7d1dfd1eef8d3e64",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
```
If I try to specify network like `docker service create -p 'mode=host,target=80' --network bridge kitematic/hello-world-nginx`, then I get error `Error response from daemon: The network bridge cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver.`

**Comment by aaronlehmann** [comment]
ping @mavenugo

**Comment by prologic** [comment]
I'm running into this too; Work-around (*which suck*):

```#!bash
$ docker network connect bridge <container_id_of_service>
```

**Comment by prologic** [comment]
Can we get this fixed for a 17.06.1 point release? This is really limiting in terms of docker stack useability

**Comment by cpuguy83** [comment]
`docker stack deploy` works with node local networks now.
You can also create swarm-scoped networks using bridge, macvlan, etc.

@prologic What needs to be fixed?

**Comment by prologic** [comment]
Can you show an example of this in a stackfile? (docker-compose.yml) v3.2

I haven't found any way to express "connect my service X to the node local
bridge network"

I have to manually:

docker network connect bridge <cid> (after hunting down the cid)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by cpuguy83** [comment]
```yaml
version: "3.2"

services:
  test:
    image: busybox
    command: top
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge
```

**Comment by prologic** [comment]
Is this expected to work with 17.03 CE ?

```#!bash
$ paste > test.yml && docker stack deploy -c test.yml test
network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"
```

Docker version:
```#!bash
Client:
 Version:      17.05.0-ce
 API version:  1.27 (downgraded from 1.29)
 Go version:   go1.8.1
 Git commit:   89658be
 Built:        
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by cpuguy83** [comment]
@prologic no, this is in 17.06

I'm going to go ahead and close this issue since this is now supported in 17.06.

**Comment by prologic** [comment]
Ahh I see thanks Brian!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Confirmed to be working in 17.06 with @cpuguy83 's snippet above. Thanks!

**Comment by danhaywood** [comment]
This doesn't seem to work in for me in Docker 17.09.0-ce-win33 (13620)

**Comment by prologic** [comment]
regression? I've not upgraded beyond 17.06-ce


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by thaJeztah** [comment]
@danhaywood what exactly do you see? It does seem to work for me on 17.09, using the example in https://github.com/moby/moby/issues/32957#issuecomment-312858586

**Comment by danhaywood** [comment]
Basically seeing the same error message.

I just uninstalled, rebooted, re-installed Docker 17.09.0-ce-win33 (13620), rebooted once more, then tried again.  Here's the transcript:

<pre>
$ cat test.yml
version: "3.2"

services:
  test:
    image: busybox
    command: top
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge

$ docker stack deploy -c test.yml test
this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again

$ docker swarm init
Swarm initialized: current node (zkm5b27jxzixquw5a0pjtxlr8) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-277y1h4zc9v4b6whrljkfet3tvdcp1jrdjhr3o96zm15ozyz73-cvkkbqs8b4kbtomdtz1wdblm7 192.168.65.2:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.


$ docker stack deploy -c test.yml test
network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"

</pre>

**Comment by rreinurm** [comment]
@danhaywood try with version: "3.3" instead

**Comment by danhaywood** [comment]
No difference, unfortunately

<pre>
$ cat test.yml
version: "3.3"

services:
  test:
    image: busybox
    command: top
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge

$ docker stack deploy -c test.yml test
network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"

</pre>

**Comment by imriss** [comment]
I am getting the same error (`"local" instead of "swarm"`) on `Ubuntu 16.04` (using `Vagrant` with `Virtualbox` backend on `Windows 10`). Any advise?

**Comment by danhaywood** [comment]
@imriss - fyi, I raised https://github.com/moby/moby/issues/35262 for my related case.  Since this issue is closed whereas that one is still open, if it's relevant you might want to comment there.

**Comment by JinnaBalu** [comment]
@danhaywood, 

Create a network 

```bash
docker network create -d overlay testservice
```
Change your test.yml file as 

```yml
version: "3.3"

services:
  test:
    image: busybox
    command: top
    networks:
      - testservice

networks:
  bridge:
    testservice:
      name: testservice
```
```bash
docker stack deploy -c test.yml teststack
```
This worked for me

**Comment by imriss** [comment]
Thanks @JinnaBalu and @danhaywood. I an following the solution proposed [here](https://github.com/moby/moby/issues/15086#issuecomment-337501603) to expose client's IP to the containers. Does you test work with `-d bridge`? Thanks. I will also repost this in [#35262](https://github.com/moby/moby/issues/35262).

**Comment by danhaywood** [comment]
Thanks, @JinnaBalu this also worked for me.  I'll close https://github.com/moby/moby/issues/35262, referencing this.

**Comment by trajano** [comment]
Please reopen the solution posted by @cpuguy83 does not work with 
```
Server:
 Version:      17.12.0-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   c97c6d6
 Built:        Wed Dec 27 20:12:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
````

**Comment by trajano** [comment]
Following the above perhaps this bug should be re-openned because it still does not support non-local networks in swarm mode

**Comment by cpuguy83** [comment]
@trajano It most definitely does support non-swarm scopped networks.

```
version: '3.4'

services:
  test:
    image: alpine
    command: top
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge
```

**Comment by trajano** [comment]
I have 
```
Server Version: 18.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: cifs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
```

My docker-compose file looks like this (just the relevant sections i.e. no volumes)

```
version: '3.4'
services:
  math:
    image: trajano.net/math
    restart: always
    network_mode: host
    deploy:
      placement:
        constraints:
        - node.hostname==docker-engine
    networks:
    - bridge
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host
networks:
  bridge:
    external:
      name: bridge
```

Key difference is the `ports` section

**Comment by trajano** [comment]
I tried taking out the "mode: host" with no luck

**Comment by trajano** [comment]
I even reduced it down to the following
```
version: '3.4'
services:
  math:
    build: .
    image: trajano.net/math
    networks:
    - bridge
networks:
  bridge:
    external:
      name: bridge
```
I still get 
> network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"

**Comment by cpuguy83** [comment]
I removed the ports section from my yaml for simplicity.
It works just fine with ports for me as well.

```
version: '3.4'

services:
  test:
    image: alpine
    command: top
    networks:
      - bridge
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host

networks:
  bridge:
    external:
      name: bridge
```

**Comment by trajano** [comment]
My `docker node ls` output is

```
$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
u7xkdyv08oa5t58icl2lb67y8 *   docker-engine       Ready               Active              Leader
j6rok48spc39c5i4v534omhcv     worker1             Ready               Active
mhvl0uaui1hta9y26vcp32a5u     worker2             Ready               Active
```

**Comment by cpuguy83** [comment]
@trajano The error you are seeing is from the client. What is the version of your docker CLI?

**Comment by trajano** [comment]
And the command I am using is `docker stack deploy -c docker-compose.yml math` however there's a bit of a mismatch since I was trying to fix this issue by upgrading the servers

```
D:\swarmprom>docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      18.03.0-ce
 API version:  1.37 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   0520e24
 Built:        Wed Mar 21 23:13:03 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by trajano** [comment]
Hmm I guess the chocolatey package was not up to date

```PS C:\WINDOWS\system32> choco upgrade docker
Chocolatey v0.10.8
Upgrading the following packages:
docker
By upgrading you accept licenses for the packages.
docker v17.10.0 is the latest version available based on your source(s).
```

**Comment by trajano** [comment]
OK it loads up now thanks.  I just have to check if it behaves like docker-compose but at least I am over the hurdle.  I'll ping the owners of https://chocolatey.org/packages/docker

**Comment by trajano** [comment]
@cpuguy83 seems that https://download.docker.com/win/static/ does not contain any newer versions of the client, do you know offhand which project I should put that issue under?

**Comment by cpuguy83** [comment]
@trajano I think the only way to get the docker CLI on Windows is by installing "Docker For Windows" or docker-ee.

**Comment by BretFisher** [comment]
Similar question: I'm trying to do this to connect a `null` network to prevent a stack from creating a overlay network (or any networking) for a global service. Can this be done? 


```yaml
version: '3.6'

services:
  images:
    image: docker
    command: sh -c "while true; do docker image prune -af; sleep 86400; done"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    networks:
      - none
    logging:
      options:
        max-size: "500k"

networks:
  none:
    external: true
    name: none
```

`docker stack deploy -c stack-prune.yml prune`

output:
Creating service prune_images
**failed to create service prune_images: Error response from daemon: could not find the corresponding predefined swarm network: network none not found**

Both cli and engine versions are 18.06.1-ce

**Comment by BretFisher** [comment]
AFAIK You don't need that network defined or listed in the service if you're just trying to publish a port in host mode. This should work:
```
service...
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host
```

**Comment by trajano** [comment]
I'm also trying to set metricbeat up with docker but according to their instructions to properly access the "host" network data (which I guess would be needed to get the actual machine host name) it requires access to `host` as the network but I can't set that on the swarm either.

**Comment by trajano** [comment]
I also tried to follow word for word the instructions in https://docs.docker.com/compose/compose-file/#host-or-none still get the same issue when I do `stack deploy` maybe that part needs to be amended

**Comment by trajano** [comment]
When using the `driver: bridge`  I get this

```
[info] Connecting to 94.100.29.74...
[WARN] Rejecting connection request from 10.255.0.2 during startup.
```

**Comment by trajano** [comment]
It should be available according to this https://github.com/moby/moby/pull/32981

**Comment by trajano** [comment]
Ok... I got it working again.  For some odd reason it won't allow me to do it from Windows docker client I had to go to the host and deploy it there.

From host

```

[root@docker-engine ~]# docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     true

```

From windows 

```
D:\dh\mylj-ws>docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by rathasenthil** [comment]
Same error (this worked fine for me in version 17.0.... ) now I upgraded to 18.0.   not working. 

network "ui" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed

Now I upgraded to version  

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by trajano** [comment]
Deploy from Linux. That’s what I did to get it to work. I created a separate bug to track that specific use case.

**Comment by rathasenthil** [comment]
It is windows 10 machine and I am running from Linux container that is what you meant right! or you want me to use the Linux desktop itself!

**Comment by BretFisher** [comment]
@trajano 

> I was hoping that to be the case, but what happens is I lose the source IP again which was the reason I was doing this setup in the first place.

my example above of just using "mode: host" in a ports publishing list for a service works with host IP in the logs, I re-confirmed this today [using my example of a traefik-reverse-proxy setup](https://github.com/BretFisher/dogvscat/blob/master/stack-proxy-global.yml). 

My example above:

- uses host network/IP on each node I constrain the service to (in my example all workers get a traefik instance in global mode).
- traefik uses overlay networks for each backend app to proxy traefik.
- traefik logs the real client IP incoming to host IP.
- I never created a "host" network. I just published the ports needed for the service with "mode: host".

**Comment by trajano** [comment]
Hi @BretFisher I did get it working again actually just not with Windows client.  I had to do it on a Linux client. I created a separate issue for the edge case #38447

**Comment by rathasenthil** [comment]
my issue still remains same the script works fine in version 17.0. and not working in Version: 18.09.0 ... everything else is same (windows 10 machine .. linux container)

error below :

network "host" is declared as external, but it is not in the right scope: "local" instead of "swarm"

network "host" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed

**Comment by agronholm** [comment]
Has anyone managed to get this to work with a local scoped network other than `bridge`? I cannot. Literally the only difference is that I'm trying to attach a service to a local network. The original example is pointless because declaring external networks at the top level doesn't do anything, you have to declare that the service wants to join them.

**Comment by agronholm** [comment]
Ok, I see now – I need to create a `swarm` scoped local network or else this cannot work. What I couldn't understand is how it worked with the `bridge` network which is `local` scoped.

**Comment by burtsevyg** [comment]
It does not work in Docker version 19.03.8, build afacb8b7f0

**Comment by cpuguy83** [comment]
Please post examples...
Here is what worked for me (just as an example testing other people's configs):

```yaml
version: '3.4'

services:
  test:
    image: alpine
    command: top
    networks:
      - bridge
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host

networks:
  bridge:
    external:
      name: bridge
```

**Comment by burtsevyg** [comment]
It's work! Thank you very much!!!

**Comment by trajano** [comment]
@burtsevyg which OS did you execute the deploy from?  Curious to see whether my related bug https://github.com/moby/moby/issues/38447 is resolved as well.

**Comment by burtsevyg** [comment]
@cpuguy83 

Hm... only from localhost:

$ telnet localhost 44422
Trying ::1...
Connected to localhost.
Escape character is '^]'.

$ telnet 10.196.10.2 44422
Trying 10.196.10.2...
telnet: Unable to connect to remote host: Connection refused

@trajano 
cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

**Comment by burtsevyg** [comment]
If I run single container with -p PORT:PORT options I can connect to this port.

**Comment by burtsevyg** [comment]
> Please post examples...
> Here is what worked for me (just as an example testing other people's configs):
> 
> ```yaml
> version: '3.4'
> 
> services:
>   test:
>     image: alpine
>     command: top
>     networks:
>       - bridge
>     ports:
>     - target: 12555
>       published: 12555
>       protocol: tcp
>       mode: host
> 
> networks:
>   bridge:
>     external:
>       name: bridge
> ```

I run my service behind reverse proxy (please see https://dockerswarm.rocks/)
with:
...
    ports:
      - "44222:44222"
...
or with
...
    ports:
      - target: 44422
        published: 44422
        protocol: tcp
        mode: host
...
networks:
  bridge:
    external:
      name: bridge
...
both without access from remote host.

**Comment by burtsevyg** [comment]
Maybe same problem https://github.com/swarmpit/swarmpit/issues/493

**Comment by burtsevyg** [comment]
My problem is traefik 1.7 related problem.

**Comment by vordenken** [comment]
> Please post examples... Here is what worked for me (just as an example testing other people's configs):
> 
> ```yaml
> version: '3.4'
> 
> services:
>   test:
>     image: alpine
>     command: top
>     networks:
>       - bridge
>     ports:
>     - target: 12555
>       published: 12555
>       protocol: tcp
>       mode: host
> 
> networks:
>   bridge:
>     external:
>       name: bridge
> ```

This worked for me as well, thank you very much !
