### ISSUE TITLE
swarm creates more service replicas than desired

### ISSUE THREAD

**Issue by Spectrik** [moby/moby#33218]
Hello,

We have got 3 physical nodes.

We face problem when creating service with option --mode global. Swarm creates more replicas than desired. In our case four. So in docker service overview (docker service ls command) we can see number of replicas **4/4 instead of 3/3**

This problem actually **does not** occur very often. We have seen it only ~ three times. For example it happened after rebooting all physical nodes at the same time but it happens.

**Removing / Recreating** service resolves this problem.
**Updating** service also resolves this problem.

But imagine situation when datacenter gets into blackout (it should not happen of course but shit happens) and all nodes gets restarted. Swarm creates wrong number of replicas for example with galera service and it actually gets broken because of it. And this is wrong.

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 182
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: lu1jofpbvaqonv7dekdhhjgsp
 Is Manager: true
 ClusterID: elw0a88zz0ytz79erse7ye8ky
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.0.20
 Manager Addresses:
  172.31.0.20:2377
  172.31.0.22:2377
  172.31.0.23:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769 GiB
Name: test0
ID: RLQV:DBLV:U3BY:CC3V:TJEK:6KYC:SYBW:D4QU:FXHU:EJM6:A43T:ONB7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by thaJeztah** [comment]
When checking those services, you actually saw 4 tasks to be deployed, or was it only the indication (`4/4`?) 

Also, do you happen to have the logs still around from around the time this happened? Perhaps there's something that may help finding the reason.

The "indicator" for global services was added in https://github.com/moby/moby/pull/27710, after which an issue was discovered (https://github.com/moby/moby/issues/32368, https://github.com/docker/swarmkit/issues/1812) and should've been fixed by https://github.com/docker/swarmkit/pull/1822 (which is part of 17.03.0 if I saw correctly)


ping @dongluochen @aaronlehmann PTAL

**Comment by Spectrik** [comment]
Yes, there were actually four containers running.

Unfortunately we do not have any log records from that moment (our fault, i admit).

**Comment by thaJeztah** [comment]
No worries; thanks for reporting - it may be difficult to replicate the situation, but I "pinged" two people that may be interested in looking into this (perhaps there have been follow up improvements that prevent this situation for the next 17.06 stable release)

**Comment by aaronlehmann** [comment]
It's possible that this was fixed by https://github.com/docker/swarmkit/pull/2113, which is on master branch and will also be included in 17.03.2. It's hard to say for sure, though.

**Comment by zopar** [comment]
I know this is an old thread, but we also seen similar behavoir when one of the nodes go down.
Example:
3 nodes and a global service is 3/3
One node go down so we have have 2/2 (this is correct)
When the node come up again we have 2/3

**Comment by mik3fly** [comment]
Hello, i have the same output
I have to do a scale=0 + update --force and then scale=desired number, in order to get the right number of replicas
I noticed that some of the undesired node are in state "Running since .." but desired state is "Shutdown".

**Comment by t0mtaylor** [comment]
This is still an issue, latest version 1.24 - docker should ensure when you set replicas to 2, only 2 run, not 3 or 4!
