### ISSUE TITLE
docker utilizes only one processor group

### ISSUE THREAD

**Issue by sebhaub** [moby/moby#33743]
**Description**

When using docker for windows server on a machine with multiple processor groups - for example by using more than one physical processor - docker only utilizes one of them.

For instance on a machine with 2 Intel Xeon Processors (each with 20 logical cores) docker info only shows a total of 20 cores. 
This is even worse on a intel xeon phi with 256 logical cores where only 64 are detected. 

**Steps to reproduce the issue:**
run docker for windows server on a machine with multiple processor groups

**Describe the results you received:**
only one processor group is detected

**Describe the results you expected:**
all processor groups are detected and can be used

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
 Containers: 17
   Running: 0
   Paused: 0
   Stopped: 17
 Images: 2
 Server Version: 17.03.1-ee-3
 Storage Driver: windowsfilter
 Windows:
  Logging Driver: json-file
 Plugins:
   Volume: local
   Network: l2bridge l2tunnel nat null overlay transparent
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
 Operating System: Windows Server 2016 Standard
 OSType: windows
 Architecture: x86_64
 CPUs: 20
 Total Memory: 191.9 GiB

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by friism** [comment]
Can you please open this on the Docker for Windows issue tracker? https://github.com/docker/for-win/issues

**Comment by sebhaub** [comment]
Done, thanks for pointing to the right place. Hopefully someone can help there.

**Comment by sebhaub** [comment]
As mentioned by @friism in the newly created [issue 838 @ docker/for-win](https://github.com/docker/for-win/issues/838) i reopen this issue as it seems to be correctly located in this repository. He also said i should ping @jhowardmsft and @darrenstahlmsft, so hopefully one of you can help me out here :)

To clarify: the issue occurs with **isolation mode process**

i am using docker-ee on Windows Server 2016 with `Default Isolation: process`. In this case docker only utilizes one processor group. 

I added some more information on the initial post.

**Comment by thaJeztah** [comment]
ping @darrenstahlmsft @jhowardmsft PTAL

**Comment by jstarks** [comment]
@sebhaub, I can see what you mean in the output of `docker info`. However, I would expect that inside the container itself, it would still see and be able to utilize all 40 cores. Can you check for this?

If so, this is probably just a straightforward bug in the output of `docker info`.
