### ISSUE TITLE
swarm mode duplicate ip addresses

### ISSUE THREAD

**Issue by fhauptmann** [moby/moby#33795]
**Description**
We recently had several issues with our cloud provider which lead us to several docker swarms failing with strange errors. One thing we observied that from time to time IP adresses in the swarm overlay network are assigned duplicate. 
We made several attempts to reproduce this issue and finally found a way to reproduce the duplicate ip adress issue. 

**Steps to reproduce the issue:**
1. Create a docker swarm with several nodes (five in our example)
2. Start some Services in the swarm with at least two replicas
3. Start some containers on swarm nodes, that are attached to the swarm overlay network
4. kill the docker process (kill -9 <main_pid_from systemctl status docker>) and/or kill some service tasks running on the same node (kill -9 <main_pid_from docker inspect>)
5. do a "docker network inspect -v <overlay_network>" on the node
6. start and stop some services in the swarm

**Describe the results you received:**
I can see that ip adresses are assigned to more than one service task. 

**Describe the results you expected:**
I would expect that every service task is assigned a unique ip adress.

**Additional information you deem important (e.g. issue happens only occasionally):**

What we tried to resolve this issue: 
- let affected node leave the swarm (docker swarm leave, docker node demote, docker node rm)
- stop the docker daemon on the affected node
- rm -rf  /var/lib/docker/*
- start the docker daemon
- rejoin the swarm

there are still duplicate ip adresses (ocker network inspect -v <overlay_network>)

next try: 
- let node leave the swarm again 
- stop the host
- delete the host
- create a new host (new host name, new ip address)
- let new host join swarm as manager

again, there are duplicate ip adresses which are assigned to the host that was completely removed from the swarm (see attached file overlay.txt)
[overlay.txt](https://github.com/moby/moby/files/1097600/overlay.txt)
**Output of `docker version`:**
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**
see attached file docker_info.txt
[docker_info.txt](https://github.com/moby/moby/files/1097641/docker_info.txt)
**Additional environment details (AWS, VirtualBox, physical, etc.):**

Environment: 
OS: CentOS 7 running in OpenStack in a public cloud.

**Comment by aaronlehmann** [comment]
ping @sanimej @fcrisciani

**Comment by kleptog** [comment]
I'm seeing similar issues. I haven't worked out exact how to reproduce it, but on one of our swarm's it's persistent: it's gotten into the state where it keeps handing out duplicate IPs. As with the reporter of this issue, we haven't found a way to recover.

We tried  stopping docker everywhere and starting it up again, but that doesn't help with the allocation. We run docker in debug mode, it seems that services do not go through reallocation when the swarm starts up again.

The output below is a the output of `docker service inspect` and you can see that the IPs 10.0.1.2/24 and 10.0.3.2/24 have been handed out multiple times.

```
# docker service inspect $(docker service ls -q) |jq '.[] | { id: .["ID"], endpoint: .["Endpoint"]["VirtualIPs"] }'
{
  "id": "cb6r7xm2jq5g88t4q1tcw5jj7",
  "endpoint": [
    {
      "NetworkID": "ks0mx4f0s08yvj527napvlj92",
      "Addr": "10.0.1.2/24"
    }
  ]
}
{
  "id": "g3w5zfoahzgeksihgt82s7ejo",
  "endpoint": [
    {
      "NetworkID": "iwe29iyzm9l9rw4bqerzevp7o",
      "Addr": "10.255.0.5/16"
    },
    {
      "NetworkID": "ks0mx4f0s08yvj527napvlj92",
      "Addr": "10.0.1.2/24"
    }
  ]
}
{
  "id": "ij41tymu422xpcfriv74di13o",
  "endpoint": [
    {
      "NetworkID": "vtq3j50pbe1zpe8yobzoai0n8",
      "Addr": "10.0.0.2/24"
    }
  ]
}
{
  "id": "lyu4ae6zwvghsv5ao7pz0wojo",
  "endpoint": [
    {
      "NetworkID": "v895nxgefy4ngcuk410fzd5ud",
      "Addr": "10.0.3.2/24"
    }
  ]
}
{
  "id": "tcn52vx0mod0uymrbu54hmd65",
  "endpoint": [
    {
      "NetworkID": "iwe29iyzm9l9rw4bqerzevp7o",
      "Addr": "10.255.0.7/16"
    },
    {
      "NetworkID": "v895nxgefy4ngcuk410fzd5ud",
      "Addr": "10.0.3.2/24"
    }
  ]
}
{
  "id": "wr0p567lvhrkc002gfx578d08",
  "endpoint": [
    {
      "NetworkID": "jne46gy48g9styh8nravrj7cu",
      "Addr": "10.0.2.2/24"
    }
  ]
}
```

It appears to only affect the Virtual IPs, the actual IPs assigned to the containers seem to be fine.

Inspecting one of the networks shows to services with the same IP:

```
# docker network inspect -v v895nxgefy4ngcuk410fzd5ud
[
    {
        "Name": "testdemo_1161",
        "Id": "v895nxgefy4ngcuk410fzd5ud",
        "Created": "2017-06-26T18:17:13.870534676+02:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.3.0/24",
                    "Gateway": "10.0.3.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "Containers": {
            "6f1e3ffe5f9f3d716420b9ebe4acee60dd90e6ec11ebb058d333543eb52c7b2c": {
                "Name": "test--1161-demostats.6mb3dwot2qsbkiw26txjcsxfp.i6pt5vanifxrmkntifctxbggw",
                "EndpointID": "332386527a6126161716c0b6676cfc63f0a175b937e7f58a93d42570bcb7c077",
                "MacAddress": "02:42:0a:00:03:04",
                "IPv4Address": "10.0.3.4/24",
                "IPv6Address": ""
            },
            "90b717a7a052c121642f3b595404a853b47637d560c6184777bdab2f76734a91": {
                "Name": "test--1161-demo.1.0ta4iqo6snlpeq5alsedbn1sf",
                "EndpointID": "8a3c8c85de3daa75955f383dd77a15a6d2cff98d4cb2c04d5545bf35466b0041",
                "MacAddress": "02:42:0a:00:03:06",
                "IPv4Address": "10.0.3.6/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4100"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "testp-a1-test-9b108a636197",
                "IP": "172.16.101.101"
            },
            {
                "Name": "testp-a2-test-ff4ed4ab4b22",
                "IP": "172.16.101.102"
            },
            {
                "Name": "testp-a3-test-84354767c398",
                "IP": "172.16.101.103"
            }
        ],
        "Services": {
            "test--1161-demo": {
                "VIP": "10.0.3.2",
                "Ports": [],
                "LocalLBIndex": 259,
                "Tasks": [
                    {
                        "Name": "test--1161-demo.1.0ta4iqo6snlpeq5alsedbn1sf",
                        "EndpointID": "8a3c8c85de3daa75955f383dd77a15a6d2cff98d4cb2c04d5545bf35466b0041",
                        "EndpointIP": "10.0.3.6",
                        "Info": {
                            "Host IP": "172.16.101.101"
                        }
                    }
                ]
            },
            "test--1161-demostats": {
                "VIP": "10.0.3.2",
                "Ports": [],
                "LocalLBIndex": 256,
                "Tasks": [
                    {
                        "Name": "test--1161-demostats.xfjsgf1ocr1e912sgdfgx8q5e.hv0pd1ibb3s5nutrk7gcqg5kt",
                        "EndpointID": "94e17aded64fa028a43fd1c2dc4358e9e6f23859d372e759385ab38e436d8e18",
                        "EndpointIP": "10.0.3.3",
                        "Info": {
                            "Host IP": "172.16.101.102"
                        }
                    },
                    {
                        "Name": "test--1161-demostats.6mb3dwot2qsbkiw26txjcsxfp.i6pt5vanifxrmkntifctxbggw",
                        "EndpointID": "332386527a6126161716c0b6676cfc63f0a175b937e7f58a93d42570bcb7c077",
                        "EndpointIP": "10.0.3.4",
                        "Info": {
                            "Host IP": "172.16.101.101"
                        }
                    },
                    {
                        "Name": "test--1161-demostats.kvhr2tg1cu2ibocz3pj0nbdkg.t1j5nvo48rqlsc4jm282opqum",
                        "EndpointID": "34facbff458b80c2c4fccb005c672b1ed04e8c40d5a183e520cc5020384bd47c",
                        "EndpointIP": "10.0.3.5",
                        "Info": {
                            "Host IP": "172.16.101.103"
                        }
                    }
                ]
            }
        }
    }
]
```

docker version
```
# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Environment: Debian Jessie on VMware, 3 node swarm

**Comment by aaronlehmann** [comment]
This might be related to https://github.com/docker/swarmkit/pull/2237

**Comment by kleptog** [comment]
Looks plausible.

I was trying to think of a way to recover and thought, maybe if I modify all the services to remove all the network attachments, that would release the pools. Then reconfiguring all the services again to cause them all to be reallocated (as an alternative to just throwing everything away). Unfortunately, that doesn't quite work:

```
# docker service inspect $(docker service ls -q) |jq -r '.[] | .["ID"] as $id | .["Endpoint"]["VirtualIPs"][]["NetworkID"] | "docker service update --detach " + $id + " --network-rm " + . ' | sh -x
+ docker service update --detach cb6r7xm2jq5g88t4q1tcw5jj7 --network-rm ks0mx4f0s08yvj527napvlj92
Error response from daemon: rpc error: code = 12 desc = networks must be migrated to TaskSpec before being changed
+ docker service update --detach g3w5zfoahzgeksihgt82s7ejo --network-rm iwe29iyzm9l9rw4bqerzevp7o
g3w5zfoahzgeksihgt82s7ejo
+ docker service update --detach ij41tymu422xpcfriv74di13o --network-rm vtq3j50pbe1zpe8yobzoai0n8
Error response from daemon: rpc error: code = 12 desc = networks must be migrated to TaskSpec before being changed
+ docker service update --detach lyu4ae6zwvghsv5ao7pz0wojo --network-rm v895nxgefy4ngcuk410fzd5ud
Error response from daemon: rpc error: code = 12 desc = networks must be migrated to TaskSpec before being changed
+ docker service update --detach tcn52vx0mod0uymrbu54hmd65 --network-rm iwe29iyzm9l9rw4bqerzevp7o
tcn52vx0mod0uymrbu54hmd65
+ docker service update --detach wr0p567lvhrkc002gfx578d08 --network-rm jne46gy48g9styh8nravrj7cu
Error response from daemon: rpc error: code = 12 desc = networks must be migrated to TaskSpec before being changed
```

It appears there's some kind of backward compatibility issue here where services created on a previous version of docker cannot be updated this way...

**Comment by kleptog** [comment]
By the way, I found some direct evidence that this is the problem. after starting docker these messages appear in the logs:

```
Jun 21 14:45:52 test-b1-demo dockerd[626]: time="2017-06-21T14:45:52.907949969+02:00" level=error msg="failed allocating task isvbo8wadm7htb881e4ahsyr5 during init" error="failed during network allocation for task isvbo8wadm7htb881e4ahsyr5: failed to allocate network IP for task isvbo8wadm7htb881e4ahsyr5 network ut82raxmtn3v8huyu9l6vueut: could not allocate IP from IPAM: Address already in use" module=node node.id=vy5n4jf43w5beeivvkdgckwwb
Jun 21 14:45:52 test-b1-demo dockerd[626]: time="2017-06-21T14:45:52.912673416+02:00" level=error msg="failed allocating task jv0n6oo1jt2hk5qkjc7zi8zsh during init" error="failed during network allocation for task jv0n6oo1jt2hk5qkjc7zi8zsh: failed to allocate network IP for task jv0n6oo1jt2hk5qkjc7zi8zsh network 004pvcgpxy5tm8xrq5y5m5caf: could not allocate IP from IPAM: Address already in use" module=node node.id=vy5n4jf43w5beeivvkdgckwwb
Jun 21 14:45:52 test-b1-demo dockerd[626]: time="2017-06-21T14:45:52.913920616+02:00" level=error msg="failed allocating task lzamkse7qbhi2m72wz70ac816 during init" error="failed during network allocation for task lzamkse7qbhi2m72wz70ac816: failed to allocate network IP for task lzamkse7qbhi2m72wz70ac816 network 1vhmng05l7u825kayllgb7mmr: could not allocate IP from IPAM: Address already in use" module=node node.id=vy5n4jf43w5beeivvkdgckwwb
Jun 21 14:45:52 test-b1-demo dockerd[626]: time="2017-06-21T14:45:52.914734690+02:00" level=error msg="failed allocating task re7r1jylf0p05uulx72znuqe6 during init" error="failed during network allocation for task re7r1jylf0p05uulx72znuqe6: failed to allocate network IP for task re7r1jylf0p05uulx72znuqe6 network 004pvcgpxy5tm8xrq5y5m5caf: could not allocate IP from IPAM: Address already in use" module=node node.id=vy5n4jf43w5beeivvkdgckwwb
Jun 21 14:45:52 test-b1-demo dockerd[626]: time="2017-06-21T14:45:52.916469417+02:00" level=error msg="failed allocating task z15yit46mgbtub2nq5jfpwpr6 during init" error="failed during network allocation for task z15yit46mgbtub2nq5jfpwpr6: failed to allocate network IP for task z15yit46mgbtub2nq5jfpwpr6 network ut82raxmtn3v8huyu9l6vueut: could not allocate IP from IPAM: Address already in use" module=node node.id=vy5n4jf43w5beeivvkdgckwwb
```

**Comment by aaronlehmann** [comment]
> It appears there's some kind of backward compatibility issue here where services created on a previous version of docker cannot be updated this way...

Yeah, it's not always possible to remove a network from a service created by an older version, because of the way networks were referenced by those older versions. I think you may be able to work around this by adding a dummy network first (to migrate to the new format) and then removing both of them.

**Comment by DerRooster** [comment]
Same issue for me. I moved our cluster to 17.06 but the issue persists. 

`Jul 14 11:33:23 FSASYDMSERVSTG02 dockerd[5444]: time="2017-07-14T11:33:23.529611967+10:00" level=error msg="fatal task error" error="starting container failed: Address already in use" module="node/agent/taskmanager" node.id=8tt6bas743shc4xh0s1y5zlji service.id=zfvxh18p3bnuvct4ujbii98i3 task.id=rvjg6k2w54ehx2bx4o1jfl9nv`

docker version
`Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: true`

I have also deleted the local kv store to work around this but the IP duplication popped up again. For now I can put a placement constraint on the service and therefore move it off a specific host and onto e.g. the one that has the IP already in use. Then the service will receive a new IP.

**Comment by fcrisciani** [comment]
ping @abhinandanpb

**Comment by kleptog** [comment]
@DerRooster  One thing about this issue is that once the cluster is in a broken state it won't recover by itself, not even if the cluster is upgraded. The above patch in swarmkit will (probably) prevent the issue happening again, but won't fix your cluster.

Internally we've documented the issue as follows:

* Run the following command:

```docker service inspect $(docker service ls -q) |grep 'Addr'|sort |uniq -d```

If this returns non-empty output you are suffering from this issue.

* To fix:

  * Remove all services with duplicate IPs. The above this gives the list of IPs. You can use the following command to give a quick overview of all the IPs of all services:

  ```docker service inspect $(docker service ls -q) |jq '.[] | { id: .["ID"], name: .["Spec"]["Name"], endpoint: .["Endpoint"]["VirtualIPs"] }'```

  * Shut down all nodes, then start all nodes, to ensure the internal IP allocation bitmaps are properly reset.

  * Recreate all services.

Since the above this issue has not reoccurred (on 17.06)

**Comment by DerRooster** [comment]
Thanks a lot @kleptog for the explanation and steps to fix. I had about 7 IP duplications in the cluster, removed all services, restarted all cluster nodes and recreated the services. For now it seems ok.

**Comment by matzegebbe** [comment]
We got the same issues with our swarm network. From time to time one service could not reach another service on a different node.
We disable the IPv6 support in linux (systcl & grub) and added a new network with a complete different subnet than our main network (172.*)

since we moved to the new subnet we did not see that issue again.

```
docker network create -d overlay --attachable --subnet 192.168.7.0/24 swarmnet
 ```
to fast add / remove network to all services

add:
```
for i in `docker service ls --format {{.Name}}`; do docker service update --network-add swarmnet $i; done;
```
remove:
```
for i in `docker service ls --format {{.Name}}`; do docker service update --network-rm swarmnet $i; done;
```

**Comment by thaJeztah** [comment]
ping @abhinandanpb have you been able to look into this?

**Comment by kleptog** [comment]
Ok, did this fix make it into 17.06, because we are still seeing this problem there. My process above does fix the issue but it returns later. Despite us not creating any new services, only updating them, we start getting new duplicates.

**Comment by kleptog** [comment]
Ok, found a fairly straight forward way to reproduce this on 17.06.2: reboot one of the nodes.

What I do is dump the state of the services before and after the reboot, like so:

```
docker service inspect $(docker service ls -q | sort) > state
```

After the reboot we often get duplicate IP addresses for services. When diff the result of the above command you get the output below. **Without any docker commands being executed, simply restarting one of the nodes causes the service IPs to be changed and duplicated**. This makes no sense, but it's what happens. And the IPs that get allocated overlap other existing services.

Note that with debugging enabled I can see no messages for ReleaseAddress or RequestAddress for these IPs. Which basically makes it look like the IP address are being made from broken state? But the entire address allocation code seems to be skipped?

```
--- state.before        2017-09-19 15:49:20.826119094 +0100
+++ state.after 2017-09-19 15:52:18.247053274 +0100
@@ -2,10 +2,10 @@
     {
         "ID": "3ghfeltiuaqehe8o61wwxcdn6",
         "Version": {
-            "Index": 88169
+            "Index": 88195
         },
         "CreatedAt": "2017-09-19T14:49:02.888033308Z",
-        "UpdatedAt": "2017-09-19T14:49:02.889995025Z",
+        "UpdatedAt": "2017-09-19T14:50:56.434654134Z",
         "Spec": {
             "Name": "test-service",
             "Labels": {
@@ -103,15 +103,15 @@
             "VirtualIPs": [
                 {
                     "NetworkID": "09bgu2kmbr8lpp43wxyaaadbs",
-                    "Addr": "10.0.2.26/24"
+                    "Addr": "10.0.2.2/24"
                 },
                 {
                     "NetworkID": "93m63jsve7ikw7ythevaqbskd",
-                    "Addr": "10.0.7.12/24"
+                    "Addr": "10.0.7.2/24"
                 },
                 {
                     "NetworkID": "2vjijgmbxq4cwhihniqeyk5i4",
-                    "Addr": "10.0.1.16/24"
+                    "Addr": "10.0.1.2/24"
                 }
             ]
         }
```

I found the tool [swarm-raftlog](https://medium.com/lucjuggery/raft-logs-on-swarm-mode-1351eff1e690) to dump the logs, and so I found that the index 88195 is when the node leadership changes:

```
Entry Index=88195, Term=45, Type=EntryNormal:
id: 104018129567492
action: <
  action: STORE_ACTION_UPDATE
  node: <
    id: "fwslc19rqb6g2svc998kf02wf"
    meta: <
      version: <
        index: 88194
      >
      created_at: <
        seconds: 1501684854
        nanos: 558535663
      >
      updated_at: <
        seconds: 1505832656
        nanos: 428782461
      >
    >
...
    status: <
      message: "Node moved to \"unknown\" state due to leadership change in cluster"
      addr: "10.54.54.101"
    >
```

And the next entry updates **all** the running services, several to bogus IPs (service ekfjd93y2qgg15v1tare811ab had this IP already and it wasn't changed in this update)

```
Entry Index=88196, Term=45, Type=EntryNormal:
id: 104018129567493
action: <
  action: STORE_ACTION_UPDATE
  service: <
    id: "3ghfeltiuaqehe8o61wwxcdn6"
    meta: <
      version: <
        index: 88195
      >
      created_at: <
        seconds: 1505832542
        nanos: 888033308
      >
      updated_at: <
        seconds: 1505832656
        nanos: 434654134
      >
    >
...
    endpoint: <
      virtual_ips: <
        network_id: "09bgu2kmbr8lpp43wxyaaadbs"
        addr: "10.0.2.2/24"
      >
      virtual_ips: <
        network_id: "93m63jsve7ikw7ythevaqbskd"
        addr: "10.0.7.2/24"
      >
      virtual_ips: <
        network_id: "2vjijgmbxq4cwhihniqeyk5i4"
        addr: "10.0.1.2/24"
      >
    >
  >
>
... + 15 or so other services, including
action: <
  action: STORE_ACTION_UPDATE
  service: <
    id: "ekfjd93y2qgg15v1tare811ab"
    meta: <
      version: <
        index: 88195
      >
      created_at: <
        seconds: 1501684989
        nanos: 923676596
      >
      updated_at: <
        seconds: 1505832656
        nanos: 434854046
      >
    >
...
    endpoint: <
      virtual_ips: <
        network_id: "09bgu2kmbr8lpp43wxyaaadbs"
        addr: "10.0.2.2/24"
      >
    >
  >
>

```

So it seems that right after the node leadership changes the services are updated with bogus Service IPs in one single large update. The IP 10.0.2.2/24 is now duplicated.

BTW, it looks like the network allocations are not logged, so the allocation status bitmap must be either transmitted some other way, or the new master must regenerate it from the data it has?

For completeness the original raft records that created the service:

```
Entry Index=88169, Term=44, Type=EntryNormal:
id: 104018130441308
action: <
  action: STORE_ACTION_CREATE
  service: <
    id: "3ghfeltiuaqehe8o61wwxcdn6"
    meta: <
      version: <
        index: 88168
      >
      created_at: <
        seconds: 1505832542
        nanos: 888033308
      >
      updated_at: <
        seconds: 1505832542
        nanos: 888033308
      >
    >
... no endpoints
>
Entry Index=88170, Term=44, Type=EntryNormal:
id: 104018130441309
action: <
  action: STORE_ACTION_UPDATE
  service: <
    id: "3ghfeltiuaqehe8o61wwxcdn6"
    meta: <
      version: <
        index: 88169
      >
      created_at: <
        seconds: 1505832542
        nanos: 888033308
      >
      updated_at: <
        seconds: 1505832542
        nanos: 889995025
      >
    >
...
    endpoint: <
      virtual_ips: <
        network_id: "09bgu2kmbr8lpp43wxyaaadbs"
        addr: "10.0.2.26/24"
      >
      virtual_ips: <
        network_id: "93m63jsve7ikw7ythevaqbskd"
        addr: "10.0.7.12/24"
      >
      virtual_ips: <
        network_id: "2vjijgmbxq4cwhihniqeyk5i4"
        addr: "10.0.1.16/24"
      >
    >
  >
>
```

```
# docker info
Containers: 22
 Running: 6
 Paused: 0
 Stopped: 16
Images: 43
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 330
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: fwslc19rqb6g2svc998kf02wf
 Is Manager: true
 ClusterID: rlcxduvxmyqajvjy7dtpq1kmj
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.54.54.101
 Manager Addresses:
  10.54.54.101:2377
  10.54.54.102:2377
  10.54.54.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.846GiB
Name: dc1_worker1
ID: KM77:6M2N:PF4V:YYO3:SMFF:IEAV:DYWN:AJJ6:ZEAL:33QR:5P4Q:2BAP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 123
 Goroutines: 244
 System Time: 2017-09-19T17:16:11.550805212+01:00
 EventsListeners: 6
Http Proxy: http://10.54.54.1:3128
Https Proxy: http://10.54.54.1:3128
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by selfisch** [comment]
Good morning everyone,

any update on this?
Still persists in version 17.09.0-ce.

Every time I am playing with one of six nodes in our test swarm environment and I have to reboot it, it produces duplicated ip's for minimum one service.
Only solution for me after that, is to destroy the swarm and build it up from scratch.

**Comment by fcrisciani** [comment]
@selfisch can you try 17.10, the IP allocation is now serialized, so till you don't get close to the exhaustion of the IP space, you should not see this behavior anymore.

**Comment by selfisch** [comment]
@fcrisciani thanks! and sure. Will give it a shot asap.

Tryed the whole morning to reproduce duplicated ip in my test env(17.09.0), without success...
On friday, I have had it several times on the same environment...

I will keep you posted about the test.

**Comment by fcrisciani** [comment]
@selfisch by chance do you use attachable containers?

**Comment by selfisch** [comment]
@fcrisciani what do you mean with "attachable" containers, "--link"?

There are only services running in our swarm. No "standalone" docker run containers. And I also mentioned all suggestions from above, including to create a seperate overlay network with a whole different private subnet.

**Comment by fcrisciani** [comment]
@selfisch the network when defined needs to have the flag --attachable set, and then you can launch containers with docker run command specifying the overlay network. If you don't specify the flag mentioned above means that the answer is no :)

**Comment by selfisch** [comment]
Ah, attachable networks. Yeah, the new created network like mentioned by @matzegebbe

    `docker network create -d overlay --attachable --subnet 192.168.7.0/24 --gateway 192.168.7.1 swarmnet`

are marked attachable and all new services started are attached to this --network.

**Comment by selfisch** [comment]
Ok, short feedback.

With existing duplicated ip in swarm at version 17.09, performing update to 17.10, the issue will not be resolved automatically.
But after updating all nodes to 17.10 and reinitializing the whole swarm, everything seems to be fine.

I restarted several nodes, several times this morning and there are no doub ips coming up. hurray :-)

**Comment by ZigmunD** [comment]
Hope the issue is resolved finally. Had multiple IP conflicts on 17.09 and decided to upgrade to 17.10 despite "atomic operation" issue.

@fcrisciani we use few containers connected to attachable overlay network. Could it make any problems?

**Comment by fcrisciani** [comment]
@ZigmunD the code path for IP allocation is the same for service's tasks and for container attached to overlay, so there should not be any difference.

In lie of transparency we are investigation a new case of duplicate IP that happened once the poll wrapped. The current workaround suggested at the moment is to kill the new container that clash and the new instance will receive the next available address so that may mitigate the problem. Will keep this ticket updated in case the case is confirmed

**Comment by websitesca** [comment]
Same problem on 17.09.0. Running an overlay network with the --attachable flag. Problem occurs when rebooting virtual machines. Some service cidrs may have duplicates, but the container ips are all unique. Looking forward to 17.10!

**Comment by fcrisciani** [comment]
@websitesca this was an issue fixed on swarmkit and libnetwork with these: https://github.com/docker/swarmkit/pull/2409, https://github.com/docker/libnetwork/pull/1985

**Comment by websitesca** [comment]
@fcrisciani hi, we've upgrade our swarm to 17.09.1-ce build 19e2cf6 but am still seeing the same problem. I've tried several times to remove all services, then put them back. First I run `docker service inspect $(docker service ls -q) |grep 'Addr'|sort |uniq -d` and I see no duplicates. Then I reboot all the nodes in the swarm and run `docker service inspect $(docker service ls -q) |grep 'Addr'|sort |uniq -d` again and then I do see duplicates. Is there something else we need to do other than simply upgrading to 17.09.1 to make the problem go away (like clear some cache somewhere)? I didn't see anything in the release notes.

**Comment by websitesca** [comment]
Possible solution... Just based on a few tests, but I've found a way to make the problem disappear (for now).

I noticed that all the duplicates were between a stack I deployed and services I created later. So I wondered what the difference was between my stack's containerspec and the ones I was creating manually. By setting this property on services I was creating AFTER I deployed my stack, the problem _seems_ to have gone away (creating using the docker api):

```
EndpointSpec: {
  Mode": "vip"
}
```

I believe the mode `vip` is the default, so it seems unlikely that this would solve the problem. But maybe the race condition that creates the duplicates somehow sees different values depending on when the default kicks in.

Can anyone else confirm if this solved their problem?

**Comment by fcrisciani** [comment]
@websitesca just one curiosity, do you see duplicates on the ingress network? ip like 10.255.X.X?
if that is the case, try to attach all your services to an overlay and retry your experiment, we are investigating a failure that is fairly easy to reproduce of overlap on the ingress for services that are only exposing a port there an not having any other network

**Comment by kleptog** [comment]
We've worked around this issue by putting everything we can in DNSRR mode. As a side effect deployment in the swarm has sped up as well (presumably because services don't need to allocate so many IP addresses).

@fcrisciani We've never seen the issue on the ingress network, but then most of our services don't connect to the ingress network.

@websitesca Interesting you mention that you experience issues with services created via the API. We are also using the API to create services, docker-py specifically. Perhaps there is a difference in the way docker-py creates services that causes an issue? I wonder if it's related to https://github.com/docker/docker-py/issues/1660 .

**Comment by websitesca** [comment]
@fcrisciani Never had duplicates on the ingress network. All our services were already attaching to an overlay network and only 3 on ingress. But I can also confirm (not sure why, since `vip` is the default) that adding `EndpointSpec: { Mode": "vip" }` to our api call to `service.create` makes the problem go away.

@kleptog hmm, yeah i see what you're talking about. it does seem related, in so far as we're talking about the spec specifics that are created with various apis. Conversely, we're not updating services, we're creating them - and also we don't get a fatal error - the services are recreated upon reboot (which maybe does a `service.update`?), but they happen to have duplicate ips. In that issue you referenced it looks like the python api call that does a `service.update` needs to follow the docker spec.

**Comment by fcrisciani** [comment]
@websitesca actually the EndpointSpec has to be populated, you are maybe triggering some other bug leaving it empty, having it explicitly populated is a valid spec, without it the spec should fail.

**Comment by websitesca** [comment]
@fcrisciani yeah I was gonna say that maybe the issue is something more superficial. anyways, that is good to know and i believe the issue is resolved for us.

**Comment by mcgoober** [comment]
Just seen this issue again using 17.12.0.
Debian 9, Docker 17.12.0, 5 Node Swarm. Leader was node 1, I stopped the docker service on node 1 and node 3 got elected leader with this log from node 3.
172.20.0.0/16 is a Swarm overlay network.
I can also confirm that by explicitly setting EndpointSpec to 'vip' this problem doesn't occur.

```
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.089601263Z" level=info msg="raft.node: 3df26cdd6b9ca2f6 lost leader 8aa0070a47725b9 at term 3" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.090749705Z" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable"
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094278372Z" level=info msg="3df26cdd6b9ca2f6 received MsgVoteResp from 5638169dcb549a49 at term 3" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094310576Z" level=info msg="3df26cdd6b9ca2f6 [quorum:3] has received 2 MsgVoteResp votes and 0 vote rejections" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094770629Z" level=info msg="3df26cdd6b9ca2f6 received MsgVoteResp from 7806e19ce2afc1ce at term 3" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094794939Z" level=info msg="3df26cdd6b9ca2f6 [quorum:3] has received 3 MsgVoteResp votes and 0 vote rejections" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094821283Z" level=info msg="3df26cdd6b9ca2f6 became leader at term 3" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.094841777Z" level=info msg="raft.node: 3df26cdd6b9ca2f6 elected leader 3df26cdd6b9ca2f6 at term 3" module=raft node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.095630852Z" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable"
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.097995658Z" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.098058880Z" level=error msg="failed to create predefined network bridge" error="name conflicts with an existing object" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.098082007Z" level=error msg="failed to create predefined network host" error="name conflicts with an existing object" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121627778Z" level=error msg="IPAM failure while releasing VIP address 172.20.0.17/16" error="invalid pool id: "
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121665630Z" level=error msg="error deallocating vip" error="invalid pool id: " vip.addr=172.20.0.17/16 vip.network=0ac9fqojng0vlm7wzm1k5rnyv
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121699088Z" level=error msg="IPAM failure while releasing VIP address 172.20.0.13/16" error="invalid pool id: "
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121713297Z" level=error msg="error deallocating vip" error="invalid pool id: " vip.addr=172.20.0.13/16 vip.network=0ac9fqojng0vlm7wzm1k5rnyv
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121734630Z" level=error msg="IPAM failure while releasing VIP address 172.20.0.19/16" error="invalid pool id: "
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121756237Z" level=error msg="error deallocating vip" error="invalid pool id: " vip.addr=172.20.0.19/16 vip.network=0ac9fqojng0vlm7wzm1k5rnyv
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121913793Z" level=error msg="IPAM failure while releasing VIP address 172.20.0.33/16" error="invalid pool id: "
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.121933718Z" level=error msg="error deallocating vip" error="invalid pool id: " vip.addr=172.20.0.33/16 vip.network=0ac9fqojng0vlm7wzm1k5rnyv
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.128984876Z" level=error msg="failed allocating task 85w4kmajsv28yby3mar1ve87x during init" error="failed to allocate network IP for task 85w4kmajsv28yby3mar1ve87x network 0ac9fqojng0vlm7wzm1k5rnyv: could not allocate IP from IPAM: Address already in use" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.129096085Z" level=error msg="failed allocating task axocfqq3j1ttosq5loby1in92 during init" error="failed to allocate network IP for task axocfqq3j1ttosq5loby1in92 network 0ac9fqojng0vlm7wzm1k5rnyv: could not allocate IP from IPAM: Address already in use" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.137237698Z" level=error msg="failed allocating task 85w4kmajsv28yby3mar1ve87x during init" error="failed to allocate network IP for task 85w4kmajsv28yby3mar1ve87x network 0ac9fqojng0vlm7wzm1k5rnyv: could not allocate IP from IPAM: Address already in use" module=node node.id=yq65b6zkmascltgu132tx10hd
Jan 11 15:52:08 lcy2-hosting-capdocker-node03 dockerd[7987]: time="2018-01-11T15:52:08.137340244Z" level=error msg="failed allocating task axocfqq3j1ttosq5loby1in92 during init" error="failed to allocate network IP for task axocfqq3j1ttosq5loby1in92 network 0ac9fqojng0vlm7wzm1k5rnyv: could not allocate IP from IPAM: Address already in use" module=node node.id=yq65b6zkmascltgu132tx10hd

```

**Comment by abhi** [comment]
@mcgoober if you are using the api directly then the spec creation should conform with the expected attributes. The spec needs to have mode as vip or dnsrr.

**Comment by fcrisciani** [comment]
@ZigmunD @mcgoober @websitesca just FYI opened a PR to address this issue on swarmkit
