### ISSUE TITLE
[Checklist] Move integration-cli tests to API tests

### ISSUE THREAD

**Issue by dnephin** [moby/moby#34623]
Related to #32866

This issue is a checklist for prioritizing specific tests that need to be removed from the integration-cli suite, and moved to the new API integration suite. 

* [ ] DockerSuite.TestRmiContainerImageNotFound
* [ ] DockerSuite.TestRmiImageIDForceWithRunningContainersAndMultipleTags
* [ ] DockerSuite.TestRunAttachDetachFromInvalidFlag
* [ ] DockerSuite.TestRunWithNanoCPUs
* [ ] DockerSuite.TestUpdateWithNanoCPUs
* [ ] DockerSwarmSuite.TestServiceLogs
* [ ] DockerSwarmSuite.TestSwarmNetworkPluginV2
* [ ] DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs

If any test also requires additional testing of the CLI please add them to the docker/cli list as well: https://github.com/docker/cli/issues/201

**Comment by dnephin** [comment]
@andrewshu @tiborvass  If you discover any test that fail in the integration test suite, please add them here (or comment and I can add them).

**Comment by andrewhsu** [comment]
@andrewhsu

**Comment by andrewhsu** [comment]
For reference, the problem with these tests are that they always fail with the latest code from docker/cli. Just a problem with the test, not a problem with the runtime code as demonstrated in https://github.com/docker/docker-ce/pull/140

**Comment by andrewhsu** [comment]
Current situation for running the `test-integration` tests from [moby/moby 184cea5](https://github.com/moby/moby/tree/184cea5ff710abde25547749e5608b24a255ba09) with a cli compiled from [docker/cli e636a53](https://github.com/docker/cli/tree/e636a5388cc92b74791c76c628d7f2ba55aab1d4) (which is the latest git commits from the respective `master` branches as of this morning) have more failures. Analyzing the list of failures with a [helper script](https://gist.github.com/seemethere/6128cb2391cd43b65b0ff4880af427e5) that checks for the 8 expected failures:

```
$ ./check_failures.sh https://jenkins.dockerproject.org/job/docker-integration-tests/108/consoleText
FOR: https://jenkins.dockerproject.org/job/docker-integration-tests/108/consoleText

Passed (thought would fail):
DockerSwarmSuite.TestServiceLogs
DockerSwarmSuite.TestSwarmNetworkPluginV2
DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs

Failed (should fail)
DockerSuite.TestRmiContainerImageNotFound
DockerSuite.TestRmiImageIDForceWithRunningContainersAndMultipleTags
DockerSuite.TestRunAttachDetachFromInvalidFlag
DockerSuite.TestRunWithNanoCPUs
DockerSuite.TestUpdateWithNanoCPUs

Failed (thought would pass):
DockerDaemonSuite.TestVolumePlugin
DockerNetworkSuite.TestConntrackFlowsLeak
DockerRegistrySuite.TestCreateByDigest
DockerRegistrySuite.TestRunByDigest
DockerRegistrySuite.TestRunImplicitPullWithNoTag
DockerSuite.TestRenameInvalidName
DockerTrustSuite.TestTrustedCreate
DockerTrustSuite.TestTrustedCreateFromBadTrustServer
DockerTrustSuite.TestTrustedIsolatedCreate
DockerTrustSuite.TestTrustedRun
DockerTrustSuite.TestTrustedRunFromBadTrustServer
```

Some of the errors in the `Failed (thought would pass)` sections may be legit bugs. Possibly `DockerNetworkSuite.TestConntrackFlowsLeak`. We're doing some analysis on them now.

**Comment by seemethere** [comment]
Confirmed `TestConntrackFlowsLeak`, issue #34693

**Comment by dnephin** [comment]
It looks like most of these failures are fixed by  docker/cli#488

The only exception is `TestRenameInvalidName`, which needs to be deleted, it's testing the CLI output strings which is just a problem with the test. We already test that in `docker/cli. I will open a PR to remove it.

**Comment by seemethere** [comment]
Can confirm that docker/cli#488 remedies all issues aside from known failures and `TestRenameInvalidName`

**Comment by dnephin** [comment]
#34695 fixes TestRenameInvalidName

**Comment by andrewhsu** [comment]
I think the 5 `DockerSuite` tests are the only ones that still fail on a regular basis with the code from master branch of docker/cli and moby/moby.

**Comment by seemethere** [comment]
Can confirm, from this morning (September 1, 2017) builds:

```
❯ bash ~/scripts/check_failures.sh https://jenkins.dockerproject.org/job/docker-integration-tests/110/consoleText
FOR: https://jenkins.dockerproject.org/job/docker-integration-tests/110/consoleText

Passed (thought would fail):
DockerSwarmSuite.TestServiceLogs
DockerSwarmSuite.TestSwarmNetworkPluginV2
DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs

Failed (should fail)
DockerSuite.TestRmiContainerImageNotFound
DockerSuite.TestRmiImageIDForceWithRunningContainersAndMultipleTags
DockerSuite.TestRunAttachDetachFromInvalidFlag
DockerSuite.TestRunWithNanoCPUs
DockerSuite.TestUpdateWithNanoCPUs

Failed (thought would pass):
DockerSuite.TestRenameInvalidName
```

**Comment by thaJeztah** [comment]
ping @cyli @n4ss could you help with porting the `DockerTrustSuite` tests? Looks like they still have to be disabled in the Docker CE repository CI, when running with a new Docker CLI.

**Comment by seemethere** [comment]
@thaJeztah @cyli @n4ss This is a major pain point for us when cutting new branches / doing nightly testing for Docker CE.

**Comment by n4ss** [comment]
@thaJeztah @seemethere yep sure, I'll port them!

**Comment by thaJeztah** [comment]
@n4ss actually ... I suspect those tests need the CLI code, so should probably be moved to the docker/cli repository (I wasn't really thinking when adding that comment); here's the list of tests that need to be looked into;

DockerTrust tests (see https://github.com/docker/docker-ce/pull/397, and https://github.com/moby/moby/issues/34623#issuecomment-326378333)

- [ ] DockerTrustSuite.TestTrustedBuildTagFromReleasesRole
- [ ] DockerTrustSuite.TestTrustedBuildTagIgnoresOtherDelegationRoles
- [ ] DockerTrustSuite.TestTrustedPullReadsFromReleasesRole
- [ ] DockerTrustSuite.TestTrustedPullIgnoresOtherDelegationRoles
- [ ] DockerTrustSuite.TestTrustedPush
- [ ] DockerTrustSuite.TestTrustedPushWithIncorrectPassphraseForNonRoot

**Comment by vvoland** [comment]
Closing in favor of https://github.com/moby/moby/issues/50159
