### ISSUE TITLE
volume mapping would fail when hostPath is a symbolic link and containerPath is a dir path on Windows 

### ISSUE THREAD

**Issue by andyzhangx** [moby/moby#34729]
**Description**
Under docker on Windows env, when HostPath is a symbolic link, ContainerPath could only be a driver letter(e.g. F:),  **while if it's a dir path(e.g. c:\mnt), the volume mapping will fail.**
Below volume mapping would fail:
`docker run -d -v C:\andy\symlink:c:\mnt --name iis microsoft/iis`

While below volume mapping would succeed:
`docker run -d -v C:\andy\symlink:e: --name iis microsoft/iis`

**Steps to reproduce the issue:**
1. On a Windows 2016 Data center host, run below command lines:
```
mkdir c:\andy
mklink /D C:\andy\symlink c:  (admin mode)
docker run -d -v C:\andy\symlink:c:\mnt --name iis microsoft/iis
docker exec -it iis cmd
```
2. In the iis container, run below command line:
`cd c:\mnt`

**Describe the results you received:**
```
C:\>cd mnt
The parameter is incorrect.
```

**Describe the results you expected:**
I could explore mnt folder

**Additional information you deem important (e.g. issue happens only occasionally):**

**I have identified this bug only exists in windows server 2016, RS3 image won’t have such issue.**

**Output of `docker version`:**

```
c:\var\lib>docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
c:\var\lib>docker info
Containers: 52
 Running: 7
 Paused: 0
 Stopped: 45
Images: 10
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14 GiB
Name: 33192acs9001
ID: VU22:O7EP:3TI7:3DBM:XAIS:2YZ3:6IRW:K6K4:4YPH:24CT:E4IA:6TEZ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: jlex2008
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @johnstep @friism ptal

**Comment by andyzhangx** [comment]
I have identified this bug only exists in windows server 2016, RS3 image won’t have such issue.

**Comment by thaJeztah** [comment]
@andyzhang so the issue is resolved in RS3? If so, ok to close this one?

**Comment by PatrickLang** [comment]
Agreed - I think we can close with recommendation to use Windows Server version 1709

**Comment by thaJeztah** [comment]
Thanks!

**Comment by andyzhangx** [comment]
@thaJeztah @PatrickLang unfortunately this bug still exists in RS3 image, it's not a so obvious issue though.
"volume mapping would fail when hostPath is a symbolic link **to a drive** and containerPath is a dir path on Windows, since I could not reopen this issue in moby, I opened a new one https://github.com/moby/moby/issues/35436 "
