### ISSUE TITLE
Swarm worker cannot connect to master if proxy is configured

### ISSUE THREAD

**Issue by stephan2012** [moby/moby#35395]
**Description**

Beginning with Docker CE 17.09, a Swarm worker connects to its master through a configured proxy. Unfortunately this fails because Docker stores the master IP addresses instead of hostnames so the master doesn't match the values configured in `NO_PROXY`.

**Steps to reproduce the issue:**
1. Setup Docker as usual. Add a proxy configuration like this to `/etc/systemd/system/docker.service.d/proxy.conf`:
    ```
    [Service]
    Environment="HTTP_PROXY=http://proxy.internal.company.com:8080" "HTTPS_PROXY=http://proxy.internal.company.com:8080" "NO_PROXY=localhost,127.0.0.1,.internal.company.com"
    ```
    Don't forget to `systemctl daemon-reload` and restart the Docker daemon.

2. Initialize swarm on the master node
    ```
    master# docker swarm init
    Swarm initialized: current node (0tf92vjqqivr9mujdd99ip6ob) is now a manager.

    To add a worker to this swarm, run the following command:

        docker swarm join --token SWMTKN-1-20n86wgp1jlfdku52x5pzlcwc6youavmzm78junqe7wtxqg4t5-2orbo6etiiknwjcfj8g52chtr 192.168.1.11:2377

    To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
    ```

3. Add a worker as indicated:
    ```
    worker# docker swarm join --token SWMTKN-1-20n86wgp1jlfdku52x5pzlcwc6youavmzm78junqe7wtxqg4t5-2orbo6etiiknwjcfj8g52chtr 192.168.1.11:2377
    ```

    Swarm join hangs because docker attempts to connect to the master through the proxy. Then it reports

    ```
    Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable
    ```

    Repeat with a FQDN and the join succeeds right away:

    ```
    # docker swarm join --token SWMTKN-1-20n86wgp1jlfdku52x5pzlcwc6youavmzm78junqe7wtxqg4t5-2orbo6etiiknwjcfj8g52chtr master.internal.company.com:2377
    This node joined a swarm as a worker.
    ```

    However, after a `dockerd` restart the worker canot connect to a master again.

**Describe the results you received:**
See above.

**Describe the results you expected:**
A swarm worker should either ignore the proxy settings, store the master FQDN instead of IP address, or have an option whether to use the proxy for master connections.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: apppool/docker
 Space Used By Parent: 405504
 Space Available: 20671299584
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 6c839q9vfo18ucl8g7yykwukg
 Is Manager: false
 Node Address: 192.168.1.12
 Manager Addresses:
  192.168.1.11:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 39.12GiB
Name: worker
ID: PLND:NJOE:YUR6:XJLP:HYEM:IO4I:KS4G:5BYP:ZOOD:BEJH:G2FR:4VVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.internal.company.com:8080
Https Proxy: http://proxy.internal.company.com:8080
No Proxy: localhost,127.0.0.1,.internal.company.com
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS is RHEL 7.4 running on vSphere 6.5

**Comment by stephan2012** [comment]
Workaround: Add master IP address(es) to `NO_PROXY`

**Comment by thaJeztah** [comment]
Thanks for reporting; while adding nodes to `NO_PROXY` (ideally, using a domain-name instead of IP-addresses) is the "correct" approach, this was indeed a change in behaviour in docker 17.07 caused by changes in an upstream dependency (https://github.com/grpc/grpc-go/pull/1098).

A fix has been merged into swarmkit to revert the change in behaviour (https://github.com/docker/swarmkit/pull/2419), which will be merged to master soon (through https://github.com/moby/moby/pull/35326), and likely be included in docker 17.11 (it's also being considered for backporting to docker 17.09 if there will be a patch release).

Earlier reports of this issue can be found in:

- https://github.com/moby/moby/issues/34825#issuecomment-331100937
- https://github.com/moby/moby/issues/34996#issuecomment-332549919
- https://github.com/moby/moby/issues/35046

**Comment by kleptog** [comment]
Just want to note that our production guys are reporting that you still cannot use a proxy for the Docker Registry in 17.12, the masters still cannot connect to each other. I have not investigated personally, they "fixed" the issue by creating an internal registry which didn't require a proxy.

**Comment by thaJeztah** [comment]
@kleptog you’re mentioning two things in that comment;

- masters not able to connect to each other 
- registry not accessible

do you have more info?

**Comment by mstenz** [comment]
This issue took me 2 days to find out. I added proxy after docker swarm init and needed to recreate the cluster which failed. It is very annoying that the name is only used at first attempt but then after a docker restart the cluster does not come up anymore. 
Can you please let me know when this get fixed?

**Comment by kleptog** [comment]
@thaJeztah I'm just saying that AFAICT this issue isn't fixed in 17.12. Configure a swarm with a proxy and the masters will attempt to use the proxy to talk to each other, which fails. The reason the registry comes into it is that the proxy is configured because the swarm has no direct internet access, and so needs the proxy to talk to the registry, but not to each other (the proxy cannot connect to the swarm itself).

But like I said I haven't personally tried it with 17.12, only 17.09.

**Comment by mstenz** [comment]
I have tried it with both 17.12 and 17.09. I think setting up a swarm cluster over a proxy doesnt make sense at all. If this was added because of a special requirement from some customers I think it would make sense to introduce seperate parameters for proxy with registry and proxy with swarm

**Comment by shezaan** [comment]
Using 17.12 added the NO_PROXY setting into /etc/systemd/system/docker.service.d/proxy.conf by adding the master node's IP address and also set the firewall

firewall-cmd --add-port=2376/tcp --permanent
firewall-cmd --add-port=2377/tcp --permanent
firewall-cmd --add-port=7946/tcp --permanent
firewall-cmd --add-port=7946/udp --permanent
firewall-cmd --add-port=4789/udp --permanent

The problem seems intermittent sometimes the masters or workers can join and sometimes they can't.
I looked at all the open issues and nothing seems to be a permanent solution.

**Comment by kshenk1** [comment]
None of this works from where I am. Our cluster nodes are behind a proxy - need to download images thru the proxy... I've set the NO_PROXY environment variable for systemd with absolutely no luck - and iptables is certainly not blocking this. I gave up with 17.09, and stayed on 17.07 until today, when I tried out 18.03.

I can't believe this is still an issue.... beyond frustrated with this.

**Comment by markvl** [comment]
For what it's worth: I'm seeing the same thing described by @kshenk1 and others: masters cannot connect to each other when a proxy is in use.

- Using Docker version 18.03.0-ce, build 0520e24
- The workaround of using `NO_PROXY` works if it's added to the managers.

**Comment by nealey** [comment]
Those of you having problems with managers joining when `http_proxy` is set, you probably need an override for containerd as well. Check #36951 for how to set `no_proxy` in a service drop-in.

**Comment by BaliStarDUT** [comment]
After docker node promote test05 , I got worker5 Down status.
After docker node promote test03 , I got worker3 Down status.

```
$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
t56wyzrf1zv     test02     Ready               Active
mslr1omr1ve     test03     Down                Active
x0wr0rsf400     test05     Down                Active
gwscff233m *   test07     Ready               Active              Leader
```
And on the workernode5 ,the log shows:
```
time="2018-08-08T16:09:19.540245652+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:09:49.696822485+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:09:49.696904074+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:10:19.861211905+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:10:19.861292741+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:10:50.114280831+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:10:50.114368904+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:11:20.273023209+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:11:20.273149844+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:11:50.446669931+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:11:50.446753874+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:12:20.706978322+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:12:20.707068592+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
time="2018-08-08T16:12:50.877844995+08:00" level=error msg="cluster exited with error: manager stopped: can't initialize raft node: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
time="2018-08-08T16:12:50.877934020+08:00" level=warning msg="Restarting swarm in 30.00 seconds"
```
It can't recover automatic.How to deal with this?

```
$ docker info
Containers: 35
 Running: 35
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: gwscff233mocepp08ipae77f4
 Is Manager: true
 ClusterID: q0wa58h5px6zndq6awtvluyvn
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: *******
 Manager Addresses:
  *********:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.16.12-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: hb-ac-test07.hb
ID: X3N2:6EQZ:XALX:SPKU:2I2Q:SU2U:7BID:JHPH:QEE6:I2JZ:WIEU:YJMM
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ablecloud
Registry: https://index.docker.io/v1/
Labels:
 containerslots=45
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tirelibirefe** [comment]
it's 2019 and problem is still exist. No_PROXY thing doesn't fix the problem.

**Comment by stephan2012** [comment]
Assuming recent software (libs have been updated meanwhile) you can try to add the node CIDRs to `no_proxy`, e.g.

```
NO_PROXY=localhost,127.0.0.1,.internal.company.com,192.168.0.0/16
```

> it's 2019 and problem is still exist. No_PROXY thing doesn't fix the problem.

**Comment by thaJeztah** [comment]
`localhost` and `127.0.0.1` should not be needed (as Golang never uses a proxy for those)

This should be fixed in Docker 18.09.4 through https://github.com/docker/swarmkit/pull/2826 and https://github.com/docker/engine/pull/170
