### ISSUE TITLE
Cannot locate Windows named pipe "docker_engine" after passing -v \\.\pipe\docker_engine:\\.\pipe\docker_engine 

### ISSUE THREAD

**Issue by ralsu091** [moby/moby#36562]
**Description**

I'm trying to mount the docker named pipe to a container in order to communicate with the docker host on the same machine. I'm using pipelist64.exe from SysInternals to inspect named pipes in the container (https://docs.microsoft.com/en-us/sysinternals/downloads/pipelist)
**Steps to reproduce the issue:**
1. Use this docker file to build the image
```
FROM microsoft/windowsservercore:latest

WORKDIR /app


COPY pipelist64.exe .
```
2. Run the container with `docker run -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -i image `
3. at the command prompt, run `pipelist64.exe -accepteula`

**Describe the results you received:**
```
PipeList v1.02 - Lists open named pipes
Copyright (C) 2005-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

Pipe Name                                    Instances       Max Instances
---------                                    ---------       -------------
InitShutdown                                      3               -1
lsass                                             5               -1
ntsvcs                                            3               -1
scerpc                                            3               -1
Winsock2\CatalogChangeListener-444-0              1                1
epmapper                                          3               -1
Winsock2\CatalogChangeListener-100-0              1                1
LSM_API_service                                   3               -1
eventlog                                          3               -1
Winsock2\CatalogChangeListener-4c0-0              1                1
TermSrv_API_service                               3               -1
Ctx_WinStation_API_service                        3               -1
wkssvc                                            6               -1
winreg                                            3               -1
cexec-141                                         1                1
cexec-142                                         1                1
cexec-143                                         1                1
Winsock2\CatalogChangeListener-228-0              1                1
Winsock2\CatalogChangeListener-4fc-0              1                1
SessEnvPublicRpc                                  3               -1
Winsock2\CatalogChangeListener-290-0              1                1
```

**Describe the results you expected:**
I expect to see `docker_engine` in the list

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 2
 Paused: 0
 Stopped: 13
Images: 11
Server Version: 18.03.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 31.94GiB
Name: DevStation9
ID: UUVQ:NZ2B:DUES:KFDG:ZSTT:VSS2:CM3J:G5GV:NXY2:CTHA:YTKX:YC4G
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 69
 System Time: 2018-03-12T10:05:02.8901376-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Please let me know if you need more information.

Thanks,

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL

**Comment by jhowardmsft** [comment]
This looks like a pipelist bug - the pipe is there and working just fine.

```
PS E:\docker\build\36562> docker build .
Sending build context to Docker daemon  53.62MB
Step 1/5 : FROM microsoft/windowsservercore
 ---> 39dc69571cfc
Step 2/5 : COPY pipelist64.exe /
 ---> Using cache
 ---> 559a962dee96
Step 3/5 : RUN dir
 ---> Using cache
 ---> 9f39b9322aa1
Step 4/5 : RUN /pipelist64.exe -accepteula
 ---> Using cache
 ---> 34cc7bd1d8c1
Step 5/5 : COPY docker.exe /
 ---> Using cache
 ---> 9f0c2ae6a48f
Successfully built 9f0c2ae6a48f
PS E:\docker\build\36562> docker run --rm -v \\.\pipe\docker_engine:\\.\pipe\docker_engine 36562 pipelist64

PipeList v1.02 - Lists open named pipes
Copyright (C) 2005-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

Pipe Name                                    Instances       Max Instances
---------                                    ---------       -------------
docker_engine                                     1                1
InitShutdown                                      3               -1
lsass                                             4               -1
ntsvcs                                            3               -1
scerpc                                            3               -1
Winsock2\CatalogChangeListener-1fa0-0             1                1
epmapper                                          3               -1
Winsock2\CatalogChangeListener-1ec4-0             1                1
LSM_API_service                                   3               -1
eventlog                                          3               -1
Winsock2\CatalogChangeListener-19e4-0             1                1
TermSrv_API_service                               3               -1
Ctx_WinStation_API_service                        3               -1
winreg                                            3               -1
wkssvc                                            5               -1
Winsock2\CatalogChangeListener-1290-0             1                1
SessEnvPublicRpc                                  3               -1
Winsock2\CatalogChangeListener-1e18-0             1                1
PS E:\docker\build\36562> docker run --rm -v \\.\pipe\docker_engine:\\.\pipe\docker_engine 36562 docker images
REPOSITORY                    TAG                                        IMAGE ID            CREATED             SIZE
36562                         latest                                     9f0c2ae6a48f        6 minutes ago       3.73GB
<none>                        <none>                                     b5778ec8f099        6 minutes ago       3.73GB
<none>                        <none>                                     f02a419d3165        10 minutes ago      3.73GB
<none>                        <none>                                     b225f211b66e        11 minutes ago      3.67GB
<none>                        <none>                                     f6e11c25dcb6        12 minutes ago      3.67GB
<none>                        <none>                                     69a5636f645a        2 days ago          945MB
microsoft/windowsservercore   10.0.17119.1001                            39dc69571cfc        3 days ago          3.67GB
microsoft/windowsservercore   latest                                     39dc69571cfc        3 days ago          3.67GB
linuxkit/runc                 7c39a68490a12cde830e1922f171c451fb08e731   7482897f3a79        3 weeks ago         9.96MB
linuxkit/alpine               b1a36f0dd41e60142dd84dab7cd333ce7da1d1f8   ed2a549ee40a        3 weeks ago         461MB
PS E:\docker\build\36562>



















```

**Comment by ralsu091** [comment]
@jhowardmsft Thank you for the reply.  So I tried running the docker client in the container, and I get the following:
```
C:\app>docker images ps
docker images ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/images/json?filters=%7B%22reference%22%3A%7B%22ps%22%3Atrue%7D%7D: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
I'm really not sure what is causing this issue. Here is the output of docker inspect:
```
[
    {
        "Id": "ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219",
        "Created": "2018-03-12T15:46:34.9366872Z",
        "Path": "c:\\windows\\system32\\cmd.exe",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1860,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-03-12T15:46:51.2856762Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:a1d5027fafa277cad39edc851839507b17c028bf1bd32ebed586139e214480ad",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219\\ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219-json.log",
        "Name": "/condescending_minsky",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "\\\\.\\pipe\\docker_engine:\\\\.\\pipe\\docker_engine"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                30,
                120
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "npipe",
                "Source": "\\\\.\\pipe\\docker_engine",
                "Destination": "\\\\.\\pipe\\docker_engine",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "ee9db7a0ab9c",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": null,
            "Cmd": [
                "c:\\windows\\system32\\cmd.exe"
            ],
            "Image": "watch",
            "Volumes": null,
            "WorkingDir": "C:\\app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "ee9db7a0ab9cef3a8efc4b2c019d8a90ace19661bbb34a4e8499f91d96e7e219",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b672d1848e409dc3520742beb515db0c31c3cefd49cd5b86cfc1edd95efb5d16",
                    "EndpointID": "c240c203a187c1ae81dc91bbef0e440da99f960a95b539556919ea220f0d3dc6",
                    "Gateway": "172.30.192.1",
                    "IPAddress": "172.30.192.7",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:c0:b3:63",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by ralsu091** [comment]
Any suggestions on how to debug this issue? Is it a permission issue? 
Here is a link to a thread on docker forums describing the same issue https://forums.docker.com/t/cannot-access-host-docker-engine-inside-container/46373/2

Thank you :)

**Comment by carlfischer1** [comment]
@ralsu091 i've been able to repro this when using hyper-v isolation as your `docker info` shows, and that it works properly when using process isolation

**Comment by johnstep** [comment]
I see a different error with Hyper-V containers (16299.309, master moby/moby and docker/cli)):

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

Removing the [check ](https://github.com/Microsoft/go-winio/blob/b7c3cf0d1286c7b62b140ed960a00b154c1b6fcc/pipe.go#L184-L186) for read-mode pipes in go-winio from the client resolves the issue. I suspect this has something to do with how the pipe is represented on VMBus. I don't know if the proxy pipe is misconfigured, partially uninitialized, or something else.

@jstarks @jhowardmsft

**Comment by PatrickLang** [comment]
MS internal bug # is 14392811. Has anyone tried this on an insider build? It looks like its already fixed there.

**Comment by ralsu091** [comment]
I am happy to test any fixes and report back the outcome.

Thanks all for taking a look at this.

**Comment by PatrickLang** [comment]
This is fixed in Windows builds > 17054. Windows Server version 1803 and Windows 10 version 1803 will have the fix once they're released.

**Comment by thaJeztah** [comment]
Thanks @PatrickLang ! Let me close this issue as this should be resolved in the upcoming Windows releases

**Comment by jsturtevant** [comment]
@PatrickLang  I was not able to get this to work with insider build.

My host machine version:

```
C:\dockerfiles-windows>ver

Microsoft Windows [Version 10.0.17133.1]
```

My Container Version:

```
C:\dockerfiles-windows>docker run -it -v //./pipe/docker_engine://./pipe/docker_engine -u ContainerAdministrator jsturtevant/docker-cli-insiders

Microsoft Windows [Version 10.0.17133.1]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>cd tools\docker

C:\tools\docker>docker.exe version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

```


The docker file that I was trying this out with: https://github.com/jsturtevant/dockerfiles-windows/blob/master/docker-client/Dockerfile.10.17133

Am I missing something?

**Comment by carlfischer1** [comment]
@jsturtevant what happens if you run

```
docker run --isolation hyperv --name engine-example --rm 
--volume '\\.\pipe\docker_engine:\\.\pipe\docker_engine' 
--volume 'C:\Program Files\Docker:C:\Docker' microsoft/windowsservercore:1709 powershell 
-Command `"(`"C:\Docker\docker.exe`" container inspect engine-example | " `"ConvertFrom-Json).Mounts | select Source, Destination"
```

**Comment by jsturtevant** [comment]
I am not able to run that command as is. Tried to modify it but still no success as the c:\docker\docker.exe is not there.

  The image in the command specified to run is 1709 anyways so wouldn't that not work?  The images I am trying on are the insider images.

**Comment by ralsu091** [comment]
I updated to Windows 10 1803 and I'm still seeing the same issue.
I tried running @carlfischer1 command but got the following:
`>docker run --isolation hyperv --name engine-example --rm --volume '\\.\pipe\docker_engine:\\.\pipe\docker_engine' --volume 'C:\Program Files\Docker:C:\Docker' microsoft/windowsservercore:1709 powershell -Command `"(`"C:\Docker\docker.exe`" container inspect engine-example | " `"ConvertFrom-Json).Mounts | select Source, Destination"
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.`

if I copy docker.exe to the container and run `docker info`:
`docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

the output of pipelist doesn't include the docker_engine pip:
```
Pipe Name                                    Instances       Max Instances
---------                                    ---------       -------------
InitShutdown                                      3               -1
lsass                                             5               -1
ntsvcs                                            3               -1
scerpc                                            3               -1
Winsock2\CatalogChangeListener-430-0              1                1
epmapper                                          3               -1
Winsock2\CatalogChangeListener-1e0-0              1                1
LSM_API_service                                   3               -1
eventlog                                          3               -1
Winsock2\CatalogChangeListener-4bc-0              1                1
TermSrv_API_service                               3               -1
Ctx_WinStation_API_service                        3               -1
wkssvc                                            7               -1
winreg                                            3               -1
cexec-5                                           1                1
cexec-6                                           1                1
Winsock2\CatalogChangeListener-310-0              1                1
Winsock2\CatalogChangeListener-4e8-0              1                1
SessEnvPublicRpc                                  3               -1
Winsock2\CatalogChangeListener-3ac-0              1                1
```

My current docker version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

docker info:
```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 15
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 31.94GiB
Name: DevStation9
ID: Y5WK:YZE7:M4DX:P5C7:KSNW:G6UU:4FDI:SMJH:OOCW:YJ5X:J55B:WXLM
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2018-05-03T12:04:45.1303034-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by carlfischer1** [comment]
@PatrickLang I can't get this to work with Win 10 RS4 either. For simplicity I copied docker.exe to c:\docker on the host:

```
C:\>cmd /s ver
Microsoft Windows [Version 10.0.17134.5]
(c) 2018 Microsoft Corporation. All rights reserved.
```

```
C:\>docker version
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:57:53 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:07:01 2018
  OS/Arch:      windows/amd64
  Experimental: true
```
```
C:\>docker run --rm --isolation hyperv --name engine-example --volume \\.\pipe\docker_engine:\\.\pipe\docker_engine --volume C:\docker:C:\docker microsoft/windowsservercore:1803 powershell -Command "C:\docker\docker.exe version"
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:57:53 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Comment by ralsu091** [comment]
Any updates on this issue?

Thanks,
Rayan

**Comment by thaJeztah** [comment]
Whoops, was a bit trigger happy; need the CLI to be updated as well; https://github.com/docker/cli/issues/1157

**Comment by thaJeztah** [comment]
CLI is merged as well; closing 👍

**Comment by amivit** [comment]
Latest version of Docker and Windows Server 2016. Wonder what I'm doing wrong :(

docker run -p 9000:9000 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine portainer/portainer
docker: Error response from daemon: named pipe mounts are not supported on this version of Windows.

**Comment by IvanJosipovic** [comment]
> Latest version of Docker and Windows Server 2016. Wonder what I'm doing wrong :(
> 
> ```
> docker run -p 9000:9000 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine portainer/portainer
> docker: Error response from daemon: named pipe mounts are not supported on this version of Windows.`
> ```
> Definitely administrator CLI

Named Pipes are only supported on Server Core 1709/1803 and Server 2019

**Comment by Type1J** [comment]
@thaJeztah Thanks for your work!
