### ISSUE TITLE
Docker daemon crash after upgrade to 5:18.09.0~3-0~debian-stretch in Swarm mode

### ISSUE THREAD

**Issue by mback2k** [moby/moby#38287]
**Description**

Docker daemon crash with the following error output:
```
INFO[2018-11-28T19:58:45.910989125+01:00] 6dc7dfde88e2230 is starting a new election at term 262462  module=raft node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.911089428+01:00] 6dc7dfde88e2230 became candidate at term 262463  module=raft node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.911126759+01:00] 6dc7dfde88e2230 received MsgVoteResp from 6dc7dfde88e2230 at term 262463  module=raft node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.911163615+01:00] 6dc7dfde88e2230 became leader at term 262463  module=raft node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.911180254+01:00] raft.node: 6dc7dfde88e2230 elected leader 6dc7dfde88e2230 at term 262463  module=raft node.id=j438j4x29hc115l10xz2ikkqh
ERRO[2018-11-28T19:58:45.911906306+01:00] error creating cluster object                 error="name conflicts with an existing object" module=node node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.912051123+01:00] leadership changed from not yet part of a raft cluster to j438j4x29hc115l10xz2ikkqh  module=node node.id=j438j4x29hc115l10xz2ikkqh
INFO[2018-11-28T19:58:45.912134442+01:00] dispatcher starting                           module=dispatcher node.id=j438j4x29hc115l10xz2ikkqh
WARN[2018-11-28T19:58:45.939988792+01:00] election tick value (10s) is different from the one defined in the cluster config (3s), the cluster may be unstable  module=node node.id=j438j4x29hc115l10xz2ikkqh
ERRO[2018-11-28T19:58:45.964888238+01:00] IPAM failure while releasing IP address 192.168.8.2/24  error="invalid pool id: "
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5592a9487abc]

goroutine 351 [running]:
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNode(0xc42e895780, 0x5592aa23aca0, 0xc42d13d580, 0xc42fb45180, 0x0, 0xc42fcc8080, 0xa, 0x10, 0xc42fc2d720)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:1045 +0x53c
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNodes(0xc42e895780, 0x5592aa23aca0, 0xc42d13d580, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:477 +0x1c0
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).doNetworkInit(0xc42e895780, 0x5592aa23aca0, 0xc42d13d580, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:154 +0x4da
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).(github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.doNetworkInit)-fm(0x5592aa23aca0, 0xc42d13d580, 0xc, 0xc)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:105 +0x40
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).init(0xc42e895780, 0x5592aa23aca0, 0xc42d13d580, 0xc42d141160, 0x0, 0x0, 0xc42b89dcf8, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:174 +0x4dd
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run.func2(0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:122 +0xbc
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run(0xc42e895780, 0x5592aa23aca0, 0xc420c4f380, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:142 +0x4e1
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader.func6(0x5592aa23aca0, 0xc420c4f380, 0xc42e895780)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1048 +0x45
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1047 +0xf34
```

**Steps to reproduce the issue:**
Unknown, not reproducable yet.

**Describe the results you received:**
Crashing docker daemon.

**Describe the results you expected:**
Working docker daemon.

**Additional information you deem important (e.g. issue happens only occasionally):**
None.

**Output of `docker version`:**

```
not available due to crash
```

**Output of `docker info`:**

```
not available due to crash
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker running on KVM-virtualized Debian 9.

**Comment by cpuguy83** [comment]
ping @dperny

**Comment by dperny** [comment]
Almost certainly this backport that I dropped: https://github.com/docker/swarmkit/pull/2767

So when you're wondering who to blame, it's me.

**Comment by dperny** [comment]
Oh, no, I _didn't_ drop this backport, it went in as part of this PR: https://github.com/docker/swarmkit/pull/2769

**Comment by mback2k** [comment]
@cpuguy83 This happened after upgrading from debian package `docker-ce=18.06.1~ce~3-0~debian` to `docker-ce=5:18.09.0~3-0~debian-stretch`.

I had to completely reinstall (with purge of /var/lib/docker) all docker nodes to get my cluster back up and running. :-(

**Comment by icedream** [comment]
Just ran into this after demoting some nodes in my Swarm, crashed this one node and prevented Docker from restarting at all afterwards. If this helps, the manager node this happened to ran on Arch Linux with most of the Swarm nodes still at 18.06.1, only a few updated to 18.09.0. This node was one of the few that had been updated.

**Comment by JonasProgrammer** [comment]
Are there any updates on this? I'm running into this problem the second time this month and I'm not really looking forward to rebuild my swarm from scratch again, losing all secrets in the process.

In my setup, there's 2 managers running 18.09.3 and another one running something 18.06.x. I know this setup is far from ideal, but I don't have access to the latter server.
The first time it happened to me, the 18.06 server was performing an upgrade to a newer version of the debian package, causing the other two daemons to crash-loop almost immediately. We fixed this by the (painful) process of killing the swarm entirely and setting it up fresh.

Now this happened again after deleting a stack (which in turn deleted a network). I read something about leader changes in the linked PR, but I doubt it was the case, as all three manager nodes were running for a longer period of time before, without any anomalies before deleting the stack.

If I can somehow help debug this issue, please let me know. Other than that, in terms of reproducing, 18.09 running on stretch with 1 node running 18.06 on jessie seems to run into that very issue quite often.

**Comment by go2null** [comment]
```
$ uname -a
Linux bradbury 4.19.31_1 #1 SMP PREEMPT Sun Mar 24 19:15:14 UTC 2019 x86_64 GNU/Linux

$ sudo xuname
Void 4.19.31_1 x86_64 GenuineIntel uptodate rrFFF

$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.12
 Git commit:        
 Built:             Sun Mar 10 23:16:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Happened after I did `docker swarm leave --force` while still manager.

Docker daemon keeps restarting.
```
$ date && sudo sv status docker
Wed Mar 27 05:23:28 EDT 2019
run: docker: (pid 17710) 1s; run: log: (pid 30015) 2469s

$ date && sudo sv status docker
Wed Mar 27 05:23:37 EDT 2019
run: docker: (pid 18771) 2s; run: log: (pid 30015) 2478s
```
`

**Comment by go2null** [comment]
Workaround/fix: `rm -rf /var/lib/docker/swarm` per https://github.com/docker/swarmkit/issues/1985#issuecomment-283191356

**Comment by tallandtree** [comment]
We had the same issue with docker-ce 18.09.6 on Ubuntu 18.04 LTS, when we tried to demote one of the managers who was "leader" at the moment. We have solved this on the managers by completely removing docker and files from the leaders and reinstalling docker. It would be nice if there is a safe way to demote a leader from the swarm. There were enough manager nodes (3) available to take over the leader role.

**Comment by tylermenezes** [comment]
Same issue and stacktrace for us last night. Wiping the raft directory was not an option as Docker had crashed on multiple machines, losing the quorum, and we needed to promote an exiting manager to leader or otherwise have to rebuild everything by hand.

Downgrading to an old version solved the problem for us.

(Dumb that this is still a problem on a major server OS 8 months later. The Docker EE page now talks exclusively about K8s so it's possible that support for Swarm is being silently ended?)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
