### ISSUE TITLE
Cannot ping docker-compose service from within a container on Windows 10

### ISSUE THREAD

**Issue by gillesgalipeau** [moby/moby#39110]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
Cannot ping docker-compose service from within a container on Windows 10.
Pinging the IP address of that service works.

**Steps to reproduce the issue:**
1. Create docker-compose-quick-servers.yml with the following content
```
version: '3.4'

services:
  server1:
    image: mcr.microsoft.com/windows/nanoserver
    container_name: Server_1
    entrypoint: ping -t localhost
  server2:
    image: mcr.microsoft.com/windows/nanoserver
    container_name: Server_2
    entrypoint: ping -t localhost
networks:
  default:
    external:
      name: nat
```
2. Run the docker containers: docker-compose -f .\docker-compose-quick-servers.yml up -d
3. Ping the other docker-compose service: docker exec Server_1 ping server2

**Describe the results you received:**
The ping fail. The same operation with the second service IP address works fine.

**Describe the results you expected:**
We should be able to ping services using its defined name.

**Additional information you deem important (e.g. issue happens only occasionally):**
It works fine in our prod environment (on Windows Server 2016).
 
**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.706)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.93GiB
Name: H198818
ID: HOKO:5CAS:SIQ2:SCLD:3TB7:A6GG:EH5X:763G:CBV5:UQMJ:BGSO:PF2Y
Docker Root Dir: E:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 36
 System Time: 2019-04-18T15:33:25.7898496-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by olljanat** [comment]
@gillesgalipeau services have DNS records only on [swarm mode](https://docs.docker.com/engine/swarm/). So if you want use it then enable swarm mode and use `docker stack deploy` instead of docker-compose.

**Comment by gillesgalipeau** [comment]
@olljanat docker [compose networking documentation](https://docs.docker.com/compose/networking/) says it should resolve the hostname between containers running on the same host based on the service defined in the docker-compose.yml.

**Comment by olljanat** [comment]
@gillesgalipeau Aa true. Then it is most probably firewall which blocks **dockerd.exe** listening DNS (UDP 53).

**Comment by AndyBuj** [comment]
I have the same issue with the exact same environment, my workstation is using a McAfee firewall service and I have implemented a set of policies* that include giving docker full access to listening to DNS UDP 53 however the bug still persists.

*the policies:
**Inbound rules**

C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe 
 All ports

All programs that meet the specified conditions 
TCP local port 445

%ProgramFiles%\Docker\Docker\resources\dockerd.exe
All UDP ports

**Outbound rules** 

%ProgramFiles%\Docker\Docker\resources\vpnkit.exe
TCP remote ports 80, 443

%ProgramFiles%\Docker\Docker\resources\vpnkit.exe
UDP remote port 53


Any ideas on what else to do?

**Comment by gillesgalipeau** [comment]
> @gillesgalipeau Aa true. Then it is most probably firewall which blocks **dockerd.exe** listening DNS (UDP 53).

@olljanat Sorry for the late reply, I was assigned to another project but I am now back to this issue. It appears that the problem exists only on systems where McAfee Endpoint Security is installed and running.

We have tried adding an exception to allow dockerd.exe to listen DNS (UDP 53) without success.

Deactivating McAfee all together resolves this issue but of course, this is not a viable solution.

Can anyone help?

**Comment by olljanat** [comment]
@gianlucaborello try allow C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe to listen any port like it was suggested by @AndyBuj  ?

**Comment by gillesgalipeau** [comment]
@olljanat Yes, actually, @AndyBuj and I were working together on that issue back then.

The problem is present, on some PCs, when the McAfee firewall is turned on, even with these policies in place.

We are trying to figure out the problem from McAfee learning capabilities but it does not give us any information on why ping to host name fails.

**Comment by gillesgalipeau** [comment]
[McAFee Endpoint Security 10.x is not supported on Windows 10 hosts](https://kc.mcafee.com/corporate/index?page=content&id=KB90041)

Hopefully McAfee will fix this soon.

Thanks for your help.

**Comment by stidiovip** [comment]
I have the same issue on ubuntu server.
