### ISSUE TITLE
rootless docker in kubernetes: "getting the final child's pid from pipe caused \"EOF\"": unknown"

### ISSUE THREAD

**Issue by lukasheinrich** [moby/moby#40068]
I am trying to run rootless docker-in-docker deployed on Kubernetes, where the docker daemon is deployed using this manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rootless
  name: rootless
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rootless
  template:
    metadata:
      labels:
        run: rootless
    spec:
      containers:
      - image: docker:19.03.1-dind-rootless
        name: rootless
        command:
        - sh
        - -c
        - dockerd-entrypoint.sh --experimental --storage-driver=vfs
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: true
          privileged: true
        resources: {}
status: {}
```

The daemon seems to start up fine but `kubectl exec`'ing into the pod, setting the DOCKER_HOST and attempting to run a container seems to break

```
kubctl create -f rootless.yml
kubectl exec -it rootless-7c94dcc5d7-gplvm sh
/ $ export DOCKER_HOST=unix:///run/user/1000/docker.sock
/ $ docker run --rm -it  busybox sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown.
/ $ command terminated with exit code 125
```

The dockerd daemon logs are collected in this gist

https://gist.github.com/lukasheinrich/e23c00240afed83066978dab8c354f52#file-logs

`kubectl version` gives

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-18T20:40:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

cc @AkihiroSuda @rochaporto

**Comment by lukasheinrich** [comment]
Thanks @AkihiroSuda. I haven't check this in a while. It's a quite old kernel. Does this need >=4.19  ?

```
[fedora@anothercluster-n4dlfgc35czn-minion-0 ~]$ uname -r
4.15.4-300.fc27.x86_64
[fedora@anothercluster-n4dlfgc35czn-minion-0 ~]$ cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)
```

**Comment by AkihiroSuda** [comment]
Does 19.03.3 work?

**Comment by AkihiroSuda** [comment]
I confirmed I can hit this issue with `docker:19.03.3-dind-rootless`, kind v0.5.1, `kindest/node:v1.16.1` (containerd 1.3.0),  on Ubuntu 19.04 kernel `5.0.0-29-generic #31-Ubuntu`

**Comment by AkihiroSuda** [comment]
@lukasheinrich What's your CRI runtime?

**Comment by AkihiroSuda** [comment]
cc @giuseppe @cyphar

**Comment by lukasheinrich** [comment]
I can confirm `docker:19.03.3-dind-rootless` also breaks for me

**Comment by lukasheinrich** [comment]
Are there any additional diagnostics we could run? Can the `kind` kubelet be run w/ debug output?

**Comment by biello** [comment]
the same problem when using minikube v1.4.0 and VirtualBox 6.0.14

**Comment by lukasheinrich** [comment]
does the new docker engine release help with this @AkihiroSuda ?

**Comment by AkihiroSuda** [comment]
Not likely, sorry.

Maybe --runtime=crun works or prints more helpful error?

**Comment by AkihiroSuda** [comment]
yes, containers/crun@ac173ad2c6d752814e4b7970612c24dc2db35117 works

**Comment by lukasheinrich** [comment]
@AkihiroSuda does the `docker:19.03.1-dind-rootless` ship with `crun` or would I have to add it myself?

**Comment by AkihiroSuda** [comment]
You need to add it by yourself. You can just override `/usr/local/bin/runc` binary.

Dockerfile for compiling crun: https://github.com/containers/crun/tree/master/contrib/static-builder-x86_64
binary release is also on plan: https://github.com/containers/crun/pull/177

**Comment by lukasheinrich** [comment]
Thanks @AkihiroSuda. This brings me a bit closer

```
(venv) lheinric@lxplus791:~/rootless% k exec -it rootless-77ff5579bc-2tzrp sh 
/ $ export DOCKER_HOST=unix:///run/user/1000/docker.sock
/ $ docker run --rm -it  busybox sh
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
0f8c40e1270f: Pull complete 
Digest: sha256:1303dbf110c57f3edf68d9f5a16c082ec06c4cf7604831669faf2c712260b5a0
Status: Downloaded newer image for busybox:latest
/ # docker: Error response from daemon: cgroups: cgroup deleted: unknown.
/ $ 
```

with logs.. I copied the new binary into `/usr/local/bin/runc` should this rather be `/usr/local/bin/crun` and  `--add-runtime crun=$(which crun)`

```
failed to parse /usr/local/bin/runc version: unknown output format: crun version 0.10.5\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL\n
```

```
time="2019-11-15T14:28:22.099956193Z" level=warning msg="failed to parse /usr/local/bin/runc version: unknown output format: crun version 0.10.5\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL\n"
time="2019-11-15T14:28:24.706856865Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99/shim.sock" debug=false pid=258 
time="2019-11-15T14:28:24.967081131Z" level=error msg="stream copy error: read /proc/self/fd/24: file already closed"
time="2019-11-15T14:28:24.976765742Z" level=error msg="failed to delete task after fail start" container=5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 error="task must be stopped before deletion: running: failed precondition" module=libcontainerd namespace=moby
time="2019-11-15T14:28:24.998916809Z" level=error msg="failed to delete failed start container" container=5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 error="cannot delete running task 5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99: failed precondition"
time="2019-11-15T14:28:25.049694305Z" level=warning msg="Ignoring Exit Event, no such exec command found" container=5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 exec-id=5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 exec-pid=272
time="2019-11-15T14:28:25.066065643Z" level=warning msg="5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 cleanup: failed to unmount IPC: umount /home/rootless/.local/share/docker/containers/5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99/mounts/shm, flags: 0x2: no such file or directory"
time="2019-11-15T14:28:25.081703579Z" level=error msg="5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99 cleanup: failed to delete container from containerd: cannot delete running task 5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99: failed precondition"
time="2019-11-15T14:28:25.100224337Z" level=error msg="Handler for POST /v1.40/containers/5ccd4f7674c45881c467d8e17e261b860908b935cbac33784d1832057b736a99/start returned error: cgroups: cgroup deleted: unknown"
```

**Comment by AkihiroSuda** [comment]
with latest daemon?

**Comment by GreeFine** [comment]
I also have the same issue i tried what you proposed @AkihiroSuda and used `crun` as runtime inside my dind-rootless but i get this error

```bash
docker: Error response from daemon: OCI runtime create failed: mount `/sys/fs/cgroup/perf_event//kubepods/besteffort/podd0988b12-759f-4370-964f-1de62a98b3e0/f594c0bf71270977f3d27fc7dd447dde40b43d671e96f78404d906b79cd09b88` to '/home/rootless/.local/share/docker/vfs/dir/6940f73da0bdca86676af1cdd1291703869c6d0b9fe3422a99e8c9206eb6792f/sys/fs/cgroup/perf_event': No such file or directory: unknown.
```
Here the environement and i used:
```
dind-deployement-0:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.6
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: crun runc
 Default Runtime: crun
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.15.0-88-generic
 Operating System: Alpine Linux v3.11 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.65GiB
 Name: dind-deployement-0
 ID: KYA4:FKO3:NZQS:D7QW:WQ67:HCIP:NICT:CHH3:NPXY:Y5AD:OJBS:4NMD
 Docker Root Dir: /home/rootless/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
WARNING: No swap limit support
```

The os-release and uname of my host
```
Linux greefine-kin 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```

And my kubernetes setup is a baremetal with kubeadm
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
And finaly the Deployment yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: devops-module

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: devops-module
    name: dind-deployement
spec:
  serviceName: dind
  podManagementPolicy: "Parallel"
  replicas: 2
  selector:
    matchLabels:
      run: dind
  template:
    metadata:
      labels:
        run: dind
    spec:
      containers:
        - name: daemon
          image: greefine/dind-daemon # FROM docker:19-dind-rootless
          securityContext:
            privileged: true
            runAsUser: 1000
            allowPrivilegeEscalation: true
          args:
            - --experimental
            - --default-runtime
            - crun
            - --add-runtime
            - crun=/usr/local/bin/crun
            - --storage-driver=vfs
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: certs
              mountPath: /certs/ca
            - name: client-certs
              mountPath: /certs/client
            - name: home
              mountPath: /root
        - name: client
          image: greefine/dind-sshd # From FROM docker:19
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: client-certs
              mountPath: /certs/client
            - name: home
              mountPath: /root
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: home
          emptyDir: {}
        - name: certs
          emptyDir: {}
        - name: client-certs
          emptyDir: {}
```

**Comment by AkihiroSuda** [comment]
Can you open an issue at https://github.com/containers/crun/issues for crun issue

**Comment by GreeFine** [comment]
@AkihiroSuda working for me with the last build of crun !
DinD Rootless yea :smile: 

The working crun version:
 ```
crun --version
crun version 0.12.2.1.29-0402
commit: 0402a428c1f2c92be021e77d7b735360bae5f77e
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```

**Comment by AkihiroSuda** [comment]
Potentially related: https://github.com/opencontainers/runc/pull/2018

**Comment by lukasheinrich** [comment]
@GreeFine do you have a example Dockerfile that builds an image that can run rootless dind?

**Comment by GreeFine** [comment]
@lukasheinrich Yes this is my repository for this project:
https://github.com/GreeFine/docker-dind-sshd

The README is not up to date, and i didn't push the crun binary
but i pushed both image on the dockerhub:
https://hub.docker.com/r/greefine/dind-daemon
https://hub.docker.com/r/greefine/dind-sshd

Also if needed the deployement yaml has been posted on my previous reply

**Comment by jappenzesr** [comment]
Great thread, thanks @GreeFine & all. Have the same need (rootless dind on k8s) and solved the issue for me as well. 

In summary: 
Preparation
```
wget https://github.com/containers/crun/releases/download/0.13/crun-0.13-static-x86_64 
# verify as needed
chmod 755 crun-0.13-static-x86_64
```
Dockerfile
```
FROM docker:19.03.7-dind-rootless
RUN mkdir -p /usr/local/bin/
COPY crun-0.13-static-x86_64 /usr/local/bin/crun
```
build & push. 

k8s configuration as per above, personally feeling more comfortable with 
```
securityContext:
  privileged: true
args: ["--experimental", "--default-runtime", "crun", "--add-runtime", "crun=/usr/local/bin/crun"]
```

**Comment by AkihiroSuda** [comment]
Did anyone identify the cause of the issue?

**Comment by zmarouf** [comment]
@AkihiroSuda I'm still encountering this on an EKS cluster. I can investigate if you let me know what to look for 😅

**Comment by frezbo** [comment]
@AkihiroSuda I was testing this on EKS cluster and it seems it only works with crun and privilged mode. This solution is also super slow, I can run rootless containers inside a pod with crun and it's superfast compared to using dind.

**Comment by jappenzesr** [comment]
I have observed significantly slower performance of the rootless-dind (out of box, run straight on a Ubuntu 18.04 VM, not in k8s) compared to normal dind when pulling large layers. The performance issue might be unrelated to this.

**Comment by AkihiroSuda** [comment]
The performance overhead is because the packets are processed in user space using VPNKit.
Switching to lxc-user-nic will provide better performance. (Needs to build custom dind image)
https://github.com/moby/moby/blob/4839b27a1fb9abcfb2142d46a6afe40bdf9f150b/contrib/dockerd-rootless.sh#L11

**Comment by moisescardoso83** [comment]
Have increased the the default vaule of "user.max_user_namespaces"?
sysctl -w user.max_user_namespaces=<put your value>
 I do suggest a value above 15000

**Comment by kfirfer** [comment]
> Great thread, thanks @GreeFine & all. Have the same need (rootless dind on k8s) and solved the issue for me as well.
> 
> In summary:
> Preparation
> 
> ```
> wget https://github.com/containers/crun/releases/download/0.13/crun-0.13-static-x86_64 
> # verify as needed
> chmod 755 crun-0.13-static-x86_64
> ```
> 
> Dockerfile
> 
> ```
> FROM docker:19.03.7-dind-rootless
> RUN mkdir -p /usr/local/bin/
> COPY crun-0.13-static-x86_64 /usr/local/bin/crun
> ```
> 
> build & push.
> 
> k8s configuration as per above, personally feeling more comfortable with
> 
> ```
> securityContext:
>   privileged: true
> args: ["--experimental", "--default-runtime", "crun", "--add-runtime", "crun=/usr/local/bin/crun"]
> ```

I just did but this is what he shows me when trying to run some container:

```
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/user/1000/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a01fa450e7243e0cf24ce9421d32cb17f9aa3c18cfdd53b31bed936715d3cf18/log.json: no such file or directory): fork/exec /usr/local/bin/crun: permission denied: <nil>: unknown.
```

**Comment by apurvc** [comment]
Great thread many thanks to @GreeFine too for his repo.

I had a use case to execute few docker files in jenkins test process and struggled with 20.10.3-dind-rootless as it was pulling huge images, found there are issues with latest which are getting fixed with 20.10.4. 

I downgraded to 19.03.15-dind-rootless and was able to get this working below is my dockerfile.

> FROM docker:19.03.15-dind-rootless
USER 0
RUN mkdir -p /usr/local/bin/
#fetch crun first using wget https://github.com/containers/crun/releases/download/0.13/crun-0.13-static-x86_64  
COPY crun-0.13-static-x86_64 /usr/local/bin/crun
RUN chmod +x /usr/local/bin/crun
USER 1000

**Comment by mo-saeed** [comment]
I have the same issue, Is there a way to install rootless with crun as default runtime ?

**Comment by thaJeztah** [comment]
@kolyshkin @cyphar any ideas on this one? Looks like a runc issue (doesn't happen with crun)

**Comment by AkihiroSuda** [comment]
I'm seeing different error with dind 20.10.5 on minikube 1.18.1

```console
$ minikube start --container-runtime=containerd
$ kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE               KERNEL-VERSION   CONTAINER-RUNTIME
minikube   Ready    control-plane,master   16m   v1.20.2   192.168.60.9   <none>        Buildroot 2020.02.10   4.19.171         containerd://1.4.3
$ cat rootless.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: rootless
spec:
  containers:
  - image: docker:20.10.5-dind-rootless
    name: rootless
    env:
    - name: DOCKER_HOST
      value: unix:///run/user/1000/docker.sock
    securityContext:
      privileged: true
$ kubectl apply -f rootless.yaml
$ kubectl exec rootless -- docker run hello-world
docker: Error response from daemon: io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/282/oom_score_adj: invalid argument
: exit status 1: unknown.
time="2021-03-23T07:53:50Z" level=error msg="error waiting for container: context canceled"
command terminated with exit code 125
```

**Comment by mo-saeed** [comment]
@AkihiroSuda Try to define Pod resources limits, I had the same issue and the POD limits fixed it.

**Comment by AkihiroSuda** [comment]
Analyzed the cause of "getting the final child's pid from pipe caused \"EOF\"": unknown" 
- Kubernetes launches dind pod with `oom_score_adj=1000`
- Dind attempts to run a container with `oom_score_adj=0` by default
- Runc does not allow this and fails with a cryptic error.

A workaround is to run `docker run` with `--oom-score-adj=1000`

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/42189

**Comment by thaJeztah** [comment]
> A workaround is to run docker run with `--oom-score-adj=1000`

Probably meant `-1000` (negative); note that the previous default score (before https://github.com/moby/moby/pull/41527 and https://github.com/moby/moby/pull/41528) of docker was `-500`

**Comment by AkihiroSuda** [comment]
No, 1000 (positive) 🙂.

Decreasing oomScoreAdj means increasing possibility of occupying the resources. So it requires the root.

**Comment by AkihiroSuda** [comment]
The fix will be in v20.10.6 (https://github.com/moby/moby/pull/42236)
