### ISSUE TITLE
name resolution not happening for services within Swarm

### ISSUE THREAD

**Issue by mukuntharajaa** [moby/moby#41633]
**Description**

I have a service in swarm, which has two processes. Each of them try to resolve a name ( via getaddrinfo ) and then bind to that ip. This is working fine with plain "docker run --network-alias ...". But not with docker swarm network-alias option.

**Steps to reproduce the issue:**
1. git clone https://gitlab.com/mukuntharajaa/dockerfiles/-/tree/master/dns-resolv
2. docker-compose build
3. docker stack deploy -c docker-compose.yml <somename>
4. docker logs <name-mentioned-in-above-line>
#here bind will fail

**Describe the results you received:**
```
md_dnsresolv.1.s53c3cccl0yj@controller    | The IP address of service1.local is: 10.0.8.2 sec=271906 nsec=800421603
md_dnsresolv.1.s53c3cccl0yj@controller    | socket creation success.
md_dnsresolv.1.s53c3cccl0yj@controller    | bind failure Address not available
md_dnsresolv.1.s53c3cccl0yj@controller    | bind failure: Address not available
md_dnsresolv.1.s53c3cccl0yj@controller    | 2020-11-02 09:09:39,094 INFO exited: dnsresolv1 (exit status 200; not expected)
md_dnsresolv.1.s53c3cccl0yj@controller    | The IP address of service2.local is: 10.0.8.2 sec=271906 nsec=803896408
md_dnsresolv.1.s53c3cccl0yj@controller    | socket creation success.
md_dnsresolv.1.s53c3cccl0yj@controller    | bind failure Address not available
md_dnsresolv.1.s53c3cccl0yj@controller    | bind failure: Address not available
```

**Describe the results you expected:**
```
dnsresolv_1  | The IP address of service1.local is: 172.26.0.2 sec=16671216 nsec=311114295
dnsresolv_1  | socket creation success.
dnsresolv_1  | Bind success. Going to sleep now for 300 seconds
dnsresolv_1  | The IP address of service2.local is: 172.26.0.2 sec=16671216 nsec=314056697
dnsresolv_1  | socket creation success.
dnsresolv_1  | Bind success. Going to sleep now for 300 seconds
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Upon inspecting network settings of this service, it shows,

```
"Networks": {
                "md_dns-net": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.8.3"
                    },
                    "Links": null,
                    "Aliases": [
                        "76d2c0346fba"
                    ],
                    "NetworkID": "spm1zkk8cz9lzy1qquiccqw23",
                    "EndpointID": "c1e8185adba8ef4ebfb6c89175fc3e715deb1b39ef24d0233197156cae72c383",
                    "Gateway": "",
                    "IPAddress": "10.0.8.3",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:08:03",
                    "DriverOpts": null
                }
            }
```

Same experiment works fine with docker run. Using same repo, please do "
docker-compose up -d"

Upon inspecting network settings of this container,
```
"Aliases": [
                        "service1.local",
                        "7d3f5d1267c1",
                        "dnsresolv",
                        "service2.local"
                    ],
```
Here one can clearly see that aliases are available. Hence, name resolution is happening.

**Output of `docker version`:**

```
docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.14.8
 Git commit:        19.03.8
 Built:             Mon Oct 26 08:24:32 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.8
  Git commit:       19.03.8
  Built:            Mon Oct 26 08:23:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3
  GitCommit:        1.3.3
 runc:
  Version:          1.0.0-rc10
  GitCommit:        1.0.0-rc10
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Output of `docker info`:**

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 6
  Paused: 0
  Stopped: 20
 Images: 20
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: y55el0kch0y84guw7ahxg7bfq
  Is Manager: true
  ClusterID: 2smaldyoei0apjqweya58ejfr
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: ====REMOVED-MANUALLY======
  Manager Addresses:
   ====REMOVED-MANUALLY======:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.3.3
 runc version: 1.0.0-rc10
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.236
 Operating System: Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.71GiB
 Name: controller
 ID: 6B2V:KG4A:YXTA:OTWN:7JI7:VGIN:6SYD:XRZK:CJ6M:3HAM:MV44:UHKX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: ====REMOVED-MANUALLY======
 HTTPS Proxy: ====REMOVED-MANUALLY======
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal hardware.

**Comment by jimlinntu** [comment]
@muayyad-alsadi I think your `docker stack deploy` command should be `docker stack deploy -c docker-compose.yml arbitrary_name`

**Comment by jimlinntu** [comment]
I have not thoroughly check it but I guess this issue should relate to how the docker cli read the compose file.

https://github.com/docker/cli/blob/5836f20c28141d10ecbf72ecc07cc5d177f683d6/cli/command/stack/loader/loader.go#L21-L50

**Comment by muayyad-alsadi** [comment]
@mukuntharajaa I guess they intended to mention you not me.

**Comment by jimlinntu** [comment]
> @mukuntharajaa I guess they intended to mention you not me.

Oops, I have fixed that. Thanks for pointing out my typo!

**Comment by mukuntharajaa** [comment]
> @mukuntharajaa I think your `docker stack deploy` command should be `docker stack deploy -c docker-compose.yml arbitrary_name`

Yes, Thats how I have actually deployed. Somehow mentioning this tag < ... > is stripped off here, which I have missed to note.
Never the less, with or without "stack deploy", i.e., even if I do, "docker service create", problem still exist. So I doubt that this has to do only with stack compose files format.

**Comment by jimlinntu** [comment]
@mukuntharajaa I think you are right. After my investigation, I find that `docker/cli` can successfully send the aliases to the docker engine. However, the engine seems to ignore it.

Here are several related files:
* https://github.com/docker/cli/blob/5836f20c28141d10ecbf72ecc07cc5d177f683d6/cli/compose/convert/service.go#L228
* https://github.com/docker/cli/blob/5836f20c28141d10ecbf72ecc07cc5d177f683d6/cli/command/stack/swarm/deploy_composefile.go#L261

Related issue: https://github.com/docker/cli/issues/744#issuecomment-619634393

**Comment by mukuntharajaa** [comment]
Capturing @jimlinntu`s email comment here.

"
This should be resolved after this merge request: docker/swarmkit#974
"

**Comment by jimlinntu** [comment]
@mukuntharajaa I found one interesting thing. If you let the service sleep for a while, the alias will work!

```yml
version: "3.0"
services:
  server:
    image: alpine:latest
    command: sh -c "sleep 20 && ping one_two_three"
    networks:
      t_net:
        aliases:
          - one_two_three

networks:
  t_net:
```

```
$ docker logs <hash>
PING one_two_three (10.0.5.64): 56 data bytes
64 bytes from 10.0.5.64: seq=0 ttl=64 time=0.099 ms
64 bytes from 10.0.5.64: seq=1 ttl=64 time=0.068 ms
64 bytes from 10.0.5.64: seq=2 ttl=64 time=0.087 ms

```

**Comment by mukuntharajaa** [comment]
@jimlinntu , thanks for the experiment. I have also added sleep in my case. Only ping works but not bind. Guess ping works differently than bind. 

`
CMD ["sh","-c","sleep 100 && /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"]
`

**Ping inside container:**

`
# docker exec -it p_dnsresolv.1.n6lc2jx1rqhc7f3bwua28tmoi sh
/ # ping service1.local
PING service1.local (10.0.10.2): 56 data bytes
64 bytes from 10.0.10.2: seq=0 ttl=64 time=0.140 ms
64 bytes from 10.0.10.2: seq=1 ttl=64 time=0.087 ms
^C
--- service1.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.087/0.113/0.140 ms
/ # ping service2.local
PING service2.local (10.0.10.2): 56 data bytes
64 bytes from 10.0.10.2: seq=0 ttl=64 time=0.079 ms
64 bytes from 10.0.10.2: seq=1 ttl=64 time=0.094 ms
^C
--- service2.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.079/0.086/0.094 ms

`

**Network settings - Aliases not found:**

`
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "41cd2b238989823e7d8ea1e71112e7279dfec682bb825041afad1f5c98a2e360",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/41cd2b238989",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "p_dns-net": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.10.3"
                    },
                    "Links": null,
                    "Aliases": [
                        "f5870ad5a892"
                    ],
                    "NetworkID": "o5g9atkqd4dy71w3am059wbe0",
                    "EndpointID": "89929f7bbe013c9f3782abeba4132f8d682401fa99b9f2e16037e6664f6b1b15",
                    "Gateway": "",
                    "IPAddress": "10.0.10.3",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:0a:03",
                    "DriverOpts": null
                }
            }

`

**Bind failure still:**

`
p_dnsresolv.1.n6lc2jx1rqhc@controller    | The IP address of service1.local is: 10.0.10.2 sec=2854872 nsec=782466582
p_dnsresolv.1.n6lc2jx1rqhc@controller    | socket creation success.
p_dnsresolv.1.n6lc2jx1rqhc@controller    | bind failure Address not available
p_dnsresolv.1.n6lc2jx1rqhc@controller    | bind failure: Address not available
p_dnsresolv.1.n6lc2jx1rqhc@controller    | 2020-12-02 06:39:05,076 INFO exited: dnsresolv1 (exit status 200; not expected)
p_dnsresolv.1.n6lc2jx1rqhc@controller    | 2020-12-02 06:39:05,077 INFO gave up: dnsresolv1 entered FATAL state, too many start retries too quickly
p_dnsresolv.1.n6lc2jx1rqhc@controller    | The IP address of service2.local is: 10.0.10.2 sec=2854872 nsec=785365403
p_dnsresolv.1.n6lc2jx1rqhc@controller    | socket creation success.
p_dnsresolv.1.n6lc2jx1rqhc@controller    | bind failure Address not available
p_dnsresolv.1.n6lc2jx1rqhc@controller    | bind failure: Address not available
p_dnsresolv.1.n6lc2jx1rqhc@controller    | 2020-12-02 06:39:05,079 INFO exited: dnsresolv2 (exit status 200; not expected)
p_dnsresolv.1.n6lc2jx1rqhc@controller    | 2020-12-02 06:39:05,079 INFO gave up: dnsresolv2 entered FATAL state, too many start retries too quickly

`

**Comment by jimlinntu** [comment]
@mukuntharajaa 

I think I conceptually know why binding an address does not work.

![image](https://user-images.githubusercontent.com/31609554/100892285-20fcc380-34f5-11eb-86d9-343e1d988fcb.png)

(Reference: <https://docs.docker.com/engine/swarm/ingress/>)

This should be a **feature** rather than a bug!
Because in swarm mode, every time you try to send a request by its "domain name",
the swarm load balancer will redirect your request to **ONE** (you do not know which one) of the containers you run.

However, in **non** swarm mode, each "domain name" will only refer to **one** container!
Therefore, that is why you can **bind**  the "domain name" by a socket while in swarm mode cannot.

**Comment by jimlinntu** [comment]
For me, if in Python, I will just listen to all IPs instead of specifying a domain name:

```python
import socket
s = socket.socket()
s.bind(("0.0.0.0", 80)
```

**Comment by mukuntharajaa** [comment]
@jimlinntu 

Thanks. So to work around the limitation in swarm mode,

1) Create server process listening to all ( 0.0.0.0 ) and publish port ( eg: 8080 ). Lets say, swarm service name as "service1"
2) Client running on host, can connect like ( 0.0.0.0:8080 )
3) Client running as another swarm service / plain-docker-container ( "service2" ), should be on same overlay network as that of (1) and then connect to "service1:8080"

**Comment by mukuntharajaa** [comment]
@jimlinntu 

I found another interesting thing while testing back and forth.

docker service create --name myserver --network name=my-o-net,alias=myserver ....

docker service inspect myserver
"Networks": [
                    {
                        "Target": "21xp555ixwrf2003gcxtu527v",
                        "Aliases": [
                            **"myserver"**
                        ]
                    }
                ],

docker inspect myserver

"Networks": {
                "my-o-net": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.4.8"
                    },
                    "Links": null,
                    "Aliases": [
                        **"8f23a2b00694"**
                    ],
                    "NetworkID": "21xp555ixwrf2003gcxtu527v",

How could "service inspect" clearly show the network alias. But not "docker inspect" ? This could be the reason for such not to work ?

**Comment by laxmanpradhan** [comment]
> / # ping service1.local
> PING service1.local (10.0.10.2): 56 data bytes
> 64 bytes from 10.0.10.2: seq=0 ttl=64 time=0.140 ms
> 64 bytes from 10.0.10.2: seq=1 ttl=64 time=0.087 ms
> ^C



> "Networks": {
> "p_dns-net": {
> "IPAMConfig": {
> "IPv4Address": "10.0.10.3"
> },
> "Links": null,
> "Aliases": [


@mukuntharajaa
Notice how when you `ping service1.local`, your IP resolves to 10.0.10.2, but then further down your post when you inspect the container, you see the IP address is actually 10.0.10.3. I wonder if this is related to the same issue I described here: #41766 where the DNS entry is incorrect (offset by 1). 

Would you be able to test your setup by first creating the services, then going `docker network inspect <networkname>` to see what the real IP addresses are for your services? Then if you exec into one of the container, try to ping to other using it's service name and see if the IP address resolves to the correct one or if it is offset by 1 (like in my situation).  You can also try `dig servicename` to see that actual A record on the docker engine DNS and see if it matches what you have under `docker network inspect`. If this is related to the issue I linked above then the IP addresses will be offset by 1.

**Comment by mukuntharajaa** [comment]
@jimlinntu Any idea on how to approach this ? I am ready to debug this. I am new to moby source code per se. If you could point out probable area, I could start from that point ?

**Comment by mukuntharajaa** [comment]
@thaJeztah Can you please help check this one. Most recent findings are [https://github.com/moby/moby/issues/41633#issuecomment-739904648](here)
