### ISSUE TITLE
OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown

### ISSUE THREAD

**Issue by fansari** [moby/moby#43969]
### Description

I cannot enter any containers with "docker exec -it ..." on my CentOS 9 VMs with  this runc version:

```
runc version 1.1.3
commit: v1.1.3-0-g6724737
spec: 1.0.2-dev
go: go1.17.13
libseccomp: 2.5.2
```

I get this error message:

```
OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown
```

### Reproduce

Run any container (e.g. alpine:latest) and try to enter it:

docker run exec <mycontainer> /bin/sh -l

OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown

### Expected behavior

It should be possible to get inside the container with "run exec -it ...".

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:29 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:12 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-142.el9.x86_64
 Operating System: CentOS Stream 9
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.569GiB
 Name: xxx
 ID: YKYV:PDNS:DNMI:S6P2:ZMFQ:HB7Q:UEU3:CKQY:JDSM:LDN3:WJQN:T6GR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Additional Info

Systems I setup with runc 1.1.2 and kernel 5.14.0-130.el9.x86_64 did not have this issue.

**Comment by thaJeztah** [comment]
Looks like the same issue that's being discussed in https://github.com/moby/moby/discussions/43960 

And a regression in runc; see https://github.com/opencontainers/runc/issues/3551

**Comment by fansari** [comment]
It was an SELinux issue. I have now found a workaround applying this:

```
setsebool -P daemons_dump_core on
```

and this policy:

```
module mydocker 1.0;

require {
        type root_t;
        type setroubleshootd_t;
        type chronyd_t;
        type init_t;
        type NetworkManager_t;
        type syslogd_t;
        type container_runtime_t;
        class file { getattr lock open read unlink };
        class bpf prog_run;
}

#============= NetworkManager_t ==============

#!!!! This avc is allowed in the current policy
allow NetworkManager_t root_t:file { getattr open read unlink };

#============= chronyd_t ==============

#!!!! This avc is allowed in the current policy
allow chronyd_t root_t:file { getattr open read };

#============= container_runtime_t ==============
allow container_runtime_t init_t:bpf prog_run;

#============= setroubleshootd_t ==============

#!!!! This avc is allowed in the current policy
allow setroubleshootd_t root_t:file { lock open read };

#============= syslogd_t ==============

#!!!! This avc is allowed in the current policy
allow syslogd_t root_t:file { getattr open read };
```

**Comment by thaJeztah** [comment]
Thanks! That looks indeed like a "less big hammer" than `setenforce 0` as workaround 😅 

FWIW; a fix is being worked on in https://github.com/opencontainers/runc/pull/3554, which is currently being reviewed, and to be included in runc 1.1.4.

**Comment by devsadds** [comment]
same issue on ubuntu 22.04 
Server Version: 20.10.17  
Kernel Version: 5.15.0-46-generic

**Comment by johnnestebann** [comment]
same here

**Comment by johnnestebann** [comment]
> 

same here

**Comment by johnnestebann** [comment]
same here

**Comment by thaJeztah** [comment]
No need to add more "+1"'s; A new release of runc is being worked on, and should hopefully be available soon; https://github.com/opencontainers/runc/pull/3564. In the meantime, as workaround;

- downgrading the containerd.io package (which included the runc binary) to 1.6.6
- or temporarily updating SELinux config https://github.com/moby/moby/issues/43969#issuecomment-1217629129 may help.

**Comment by ahAskari** [comment]
Check this way

https://stackoverflow.com/a/73431533/14596729

**Comment by vimarshacooray** [comment]
Same issue, was able to temporarily resolve it by restarting the specific container.

don't wont to restart the entire docker service on production

**Comment by JeffreyDin** [comment]
Check this way

https://askubuntu.com/questions/1424317/docker-20-10-ubuntu-22-04-oci-runtime-exec-failed

Downgrade containerd.io to 1.6.6:
sudo apt install containerd.io=1.6.6-1

**Comment by alissoncorsair** [comment]
> Check this way
> 
> https://askubuntu.com/questions/1424317/docker-20-10-ubuntu-22-04-oci-runtime-exec-failed
> 
> Downgrade containerd.io to 1.6.6: sudo apt install containerd.io=1.6.6-1

it worked, thankssss :)))))

**Comment by thaJeztah** [comment]
We published `containerd.io` packages for containerd v1.6.8 with runc v1.1.4 (which contains a fix for this issue) to download.docker.com; if you installed docker and containerd using our RPM or DEB packages, then updating the package should resolve this issue.

The static binary packages (`.tgz`) for docker did not yet have runc v1.1.3 includes, so should not be affected, but an upcoming v20.10.18 patch release will contain containerd v1.6.8 and runc v1.1.4, and should likely arrive somewhere next week.

**Comment by playground** [comment]
Have the same problem with docker exec -it on my Mac after the update yesterday.

**Comment by thaJeztah** [comment]
Current versions of docker desktop are at containerd v1.6.6, and runc v1.1.2, so that sounds like a different issue.

**Comment by rdziwinski** [comment]
I upgraded to runc 1.1.4 and containerd to v1.6.8 and still the same problem:
```
root@w02:~# runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d
spec: 1.0.2-dev
go: go1.17.13
libseccomp: 2.5.1
root@w02:~# containerd --version
containerd containerd.io 1.6.8 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
root@w02:~# crictl exec -it 7a5366e15a65b  ls
FATA[0000] execing command in container: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "4dd0544bf0ceffd100105d693e71d60633e9cd8347b1744af7a146b32fc0176f": OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown 
```

**Comment by thaJeztah** [comment]
@rdziwinski could you perhaps open a new ticket with details (as asked in the form if you open the ticket)? It _could_ still  be the same issue, but also could be something else resulting in the same error. Just to avoid potentially conflating separate issues, it'd be good to start with a fresh ticket.

I see you're using `crictl exec`; when opening the ticket

- could you also try if you see the same issue when starting a fresh container using `docker run` and `docker exec` (to narrow down possible causes).
- do you know if dockerd was restarted after upgrading containerd? (I recall we had issues where containerd shims were kept in memory, causing odd failures that were resolved after restarting).

**Comment by TonyyCruz** [comment]
I'm having the same problem... I did a docker-compose down and up it back, so I was able to access it, but I need to do this every time I restart the system.

**Comment by vimarshacooray** [comment]
for me the case seems to be related to Config server Firewall adjusting iptables.  

> Same issue, was able to temporarily resolve it by restarting the specific container.
> 
> don't wont to restart the entire docker service on production

**Comment by logopk** [comment]
Same situation here, but in my case I think it's "live-restore": true". After installation of runc 1.1.4 the running containers aren't restarted. After one restart I have not found this problem anymore.

**Comment by thaJeztah** [comment]
Ah, yes, with "live-restore" I can see that being expected, as indeed the existing containers would not get the updated runtimes.

**Comment by yassinecc** [comment]
FYI, you can upgrade containerd.io to 1.6.8 it should fix the issue as well

**Comment by thaJeztah** [comment]
Yup; https://github.com/moby/moby/issues/43969#issuecomment-1228358971

**Comment by houssem11957** [comment]
Same problem here : 
Docker (Swarm enabled) : Docker version 20.10.17, build 100c701
OS :Debian bullseye 11

**Comment by jacek-9999** [comment]
Restart container and try again.

**Comment by Martin-Luther** [comment]
I had the same problem, but only with one pod. I had to rollout restart the pod/deployment.

```tty
$ runc --version
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.21.11
libseccomp: 2.3.3
```

```tty
$ containerd --version
containerd github.com/containerd/containerd v1.7.22 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
```

```tty
$ uname -r
5.10.0-0.deb10.26-amd64
```

```tty
$ sudo dpkg -s kubeadm
Package: kubeadm
Status: hold ok installed
Priority: optional
Section: admin
Installed-Size: 56984
Maintainer: Kubernetes Authors <dev@kubernetes.io>
Architecture: amd64
Version: 1.31.1-1.1
Depends: cri-tools (>= 1.30.0)
Description: Command-line utility for administering a Kubernetes cluster
 Command-line utility for administering a Kubernetes cluster.
Homepage: https://kubernetes.io
```
