### ISSUE TITLE
28.0.0: Cannot start with iptables=true

### ISSUE THREAD

**Issue by xplodwild** [moby/moby#49505]
### Description

After upgrading from Docker 27.5.1 to Docker 28.0.0, the Daemon cannot start with the following error:

```
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to register "bridge" driver: invalid argument
```

No other error is displayed, including in debug log mode. Starting dockerd with --iptables=false allows the daemon to start, however that's not desired. This happens on an ARM board with a custom-built kernel, so I suspect a missing kernel module, but nothing seems to indicate what could be missing.

Rolling back to 27.5.1 makes it work again without any other change.

There are other reports on NVidia forums with ARM development boards: https://forums.developer.nvidia.com/t/docker-ce-28-0-0-wont-run-under-current-l4t/324420
I haven't tried on a Raspberry Pi but I suspect this could be reproduceable there.

### Reproduce

1. Try to start Docker on an ARM board

### Expected behavior

Docker should start properly, without errors, with iptables enabled

### docker version

```bash
docker version
Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:32 2025
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:41:32 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
docker info (from a working 27.5.1 build)
Client: Docker Engine - Community
 Version:    27.5.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 27.5.1
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.198
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.814GiB
 Name: tripod-entree
 ID: 12a560d5-4165-4333-972b-b38f25c99d0f
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

**Comment by robmry** [comment]
Hi @xplodwild - does the kernel have `CONFIG_IP_SET` enabled?

**Comment by xplodwild** [comment]
> Hi [@xplodwild](https://github.com/xplodwild) - does the kernel have `CONFIG_IP_SET` enabled?

Hi, I just checked and not, CONFIG_IP_SET is not set in our config:

```
# CONFIG_IP_SET is not set
# CONFIG_IP_VS is not set
```

Is this the only flag needed, or are there other new requirements for Docker 28?

**Comment by robmry** [comment]
I think it's these ...

```
CONFIG_IP_SET=m
CONFIG_IP_SET_HASH_NET=m
CONFIG_NETFILTER_XT_SET=m
```

(With thanks to @heitbaum - https://github.com/moby/moby/issues/49503#issuecomment-2671590908)

**Comment by taylorsilva** [comment]
I was also getting this error. Can confirm that setting these options resolved the issue. My Docker daemon was able to start after.

> I think it's these ...
> 
> ```
> CONFIG_IP_SET=m
> CONFIG_IP_SET_HASH_NET=m
> CONFIG_NETFILTER_XT_SET=m
> ```

**Comment by rFond** [comment]
Hi, I have the same problem, but I can't modify CONFIG_IP_SET on all my devices.
I hope an alternative solution will be available.

**Comment by robmry** [comment]
> Hi, I have the same problem, but I can't modify CONFIG_IP_SET on all my devices. I hope an alternative solution will be available.

Hi @rFond - not for iptables, but native nftables support is coming soon, which should solve this issue.

**Comment by rFond** [comment]
When will this patch be implemented?

**Comment by robmry** [comment]
> When will this patch be implemented?

There's no release date yet, but the work is in-progress.

**Comment by virtualJonesie** [comment]
Basic fresh install of Ubuntu and Docker 28.0 and encountering this issue. 

I added the above environment variables to /etc/environment and verified they were present with printenv and I receive the same issue. Not resolved.

**Comment by thaJeztah** [comment]
The `check-config.sh` script in this repository was updated in https://github.com/moby/moby/pull/49510 to also show if the config is applied correctly; you can download if from here to check if your system has the options set correctly; https://raw.githubusercontent.com/moby/moby/refs/heads/master/contrib/check-config.sh

**Comment by virtualJonesie** [comment]
```
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: cgroupv2
  Controllers:
  - cpu: available
  - cpuset: available
  - io: available
  - memory: available
  - pids: available
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_MANGLE: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_NETFILTER_XT_MARK: enabled (as module)
- CONFIG_NETFILTER_XT_SET: missing
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_IP_SET: missing
- CONFIG_IP_SET_HASH_NET: missing
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_CGROUP_BPF: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_SECCOMP_FILTER: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
    (cgroup swap accounting is currently enabled)
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_PROTO_TCP: missing
- CONFIG_IP_VS_PROTO_UDP: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_SECURITY_SELINUX: enabled
- CONFIG_SECURITY_APPARMOR: missing
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
    - CONFIG_BRIDGE_VLAN_FILTERING: enabled
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: missing
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: missing
      - CONFIG_XFRM_USER: missing
      - CONFIG_XFRM_ALGO: missing
      - CONFIG_INET_ESP: missing
      - CONFIG_NETFILTER_XT_MATCH_BPF: missing
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: missing
    - CONFIG_NF_CONNTRACK_FTP: missing
    - CONFIG_NF_NAT_TFTP: missing
    - CONFIG_NF_CONNTRACK_TFTP: missing
- Storage Drivers:
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000


```

**Comment by virtualJonesie** [comment]
Here is the output from printenv:
```
CONFIG_IP_SET=m
CONFIG_NETFILTER_XT_SET=m
CONFIG_IP_SET_HASH_NET=m
SHELL=/bin/bash
PWD=/home/dave
LOGNAME=dave
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/dave
LANG=en_US.UTF-8
SSH_CONNECTION=fe80::e7ac:685d:2e5e:e5ee%enP8p1s0 49390 fe80::4ba3:f1f0:4a74:5fa9%enP8p1s0 22
XDG_SESSION_CLASS=user
TERM=xterm
SHLVL=1
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=fe80::e7ac:685d:2e5e:e5ee%enP8p1s0 49390 22
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/0
_=/usr/bin/printenv

```

**Comment by robmry** [comment]
> I added the above environment variables to /etc/environment and verified they were present with printenv and I receive the same issue. Not resolved.

Hi @virtualJonesie - they're kernel modules that need to be available ... the environment-variable-looking values are for a kernel config file (`CONFIG_IP_SET=m` means include `IP_SET` as a loadable module). You'll need a kernel built with those settings.

**Comment by robmry** [comment]
> Just so I understand: Is the out-of-the box Ubuntu kernel not sufficient to run Docker 28?

The kernel installed with a desktop Ubuntu 24.04 has the modules ... but it might depend on which kernel you're using - https://discourse.ubuntu.com/t/kernel-configuration-in-ubuntu/35857

**Comment by thaJeztah** [comment]
cc @elezar in case you know who's maintaining the kernel config for those

**Comment by maniani-dev** [comment]
That cost me 4 hours today trying to fix it, lucky I came accross this so I decided to downgrade instead. 

Everything was fine until I upgraded to the latest version of cloudflared. Anyway, the solution on my arm64 machines was downgrading Docker to version 27.0.0-rc.2. 

If anyone else runs into this, here's what worked for me:

Run these commands exactly:

```bash
sudo apt install docker-ce=5:27.0.0~rc.2-1~ubuntu.20.04~focal docker-ce-cli=5:27.0.0~rc.2-1~ubuntu.20.04~focal containerd.io
sudo apt-mark hold docker-ce docker-ce-cli containerd.io
sudo systemctl restart docker
```

To verify it's working, run:

```bash
docker --version
sudo docker run hello-world
```

I confirmed this fix on two of my arm64 machines and a Jetson Orin Nano Super.

**Comment by thaJeztah** [comment]
> the solution on my arm64 machines was downgrading Docker to version 27.0.0-rc.2.

Be aware that 27.0.0-rc.2 is a _pre relase_ of v27.x; the last version before v28.0 is (currently) v27.5.1; instructions mentioned above are for Ubuntu 20.10. If you need to downgrade or "pin" to a specific version, instructions can be found in the installation instructions in the docs for your distro under the "Install using the apt repository" (or Install using the rpm repository for RPM-based distros) section, which has a "Install specific version" tab that outlines how to get a list of versions to select from for a package, e.g. for Ubuntu; [Install using the apt repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) 

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/c4c25e4f-002e-4db9-93b7-2cb03fc2862a" />

**Comment by robmry** [comment]
> > Hi, I have the same problem, but I can't modify CONFIG_IP_SET on all my devices. I hope an alternative solution will be available.
> 
> Hi [@rFond](https://github.com/rFond) - not for iptables, but native nftables support is coming soon, which should solve this issue.

Hi all ... good news, new plan - we'll drop the use of ipset in 28.0.1, it's proved too disruptive. Please bear with us a for couple of days and we'll get it shipped.
