### ISSUE TITLE
Colons in pathnames

### ISSUE THREAD

**Issue by blakery** [moby/moby#8604]
This references issue #8438 : Unable to map docker volume with colon.

In light of the announcement re windows support, the scope of this has changed considerably. As I had posted to the dev group, I see the following solutions (revised for newly available information):
1. Change nothing, but specify that colons are not accepted in path names. Obviously the simplest solution, as it only involves a sentence or so in the documentation. Before, I didn't like this, because it seemed sloppy and incomplete. While colons are not guaranteed to be portable by Posix, they are not forbidden either, and in practice most operating systems allow it. With the addition of adding windows support, this is now outright impossible (fine by me). C:foo will have to be perfectly valid.
2. As suggested by the op: Changing the behavior to only split at the start of an absolute pathname. I've looked at this, and it's relatively simple to implement, but does raise some issues about some error conditions and how they're handled. More importantly, with windows support, this no longer makes sense. C:/foo would still appear as "C" "/foo". 
3. Implement escape characters. Before this seemed like overkill. Now it seems like the a very reasonable solution.
4. Reconfigure how pathname lists are handled entirely. This could be something like using quotes, or allowing (but not requiring) quotes, and ensure that anything within them will be taken as a single path name. Such as: -v="C:/foo":/tmp/foo . As I'm writing this, and thinking it through, this is seeming more plausible.
5. Any other suggestions?

1 and 2 are no longer plausible. 3 is not bad, but could get cumbersome (especially for windows users). I think that I could implement 4 with little overhead.
- Blake Geno

**Comment by ruffsl** [comment]
Just hit this bug as well, quite annoying.

**Comment by frol** [comment]
My worst day ever... hit 5 bugs only today :(
Is there any workaround?

**Comment by thaJeztah** [comment]
ping @calavera are you working on this for the volumes rewrite?

**Comment by calavera** [comment]
Nope, it's the first time I see this issue.

**Comment by thaJeztah** [comment]
@calavera this might be a problem, because (I think) the new Volume Driver feature will interpret `C:` as the (driver-)name? Might have my wires crossed on that, not sure

**Comment by calavera** [comment]
I don't have a windows box to test it right now, but I'd expect go's `filepath.IsAbs` to know what an absolute path is in windows. Nothing has changed in that regard after the refactoring.

**Comment by cpuguy83** [comment]
@calavera Correct, it does handle that.

**Comment by murphyke** [comment]
+1  In one of my projects, directories on a Linux system are routinely created with colons in their names, and I hurl shellacked gourds around in a most shocking fashion when I have to mount one of these into a container.

**Comment by christoph-kluge** [comment]
+1 as I also hit this bug, just realised after 1 hour of investigating - mostly by accident I added `:ro` and `:rw` and then I saw the exception trace which told me it has an incorrect format.

**Comment by Jaykah** [comment]
+1 Having the same problem, but with a CIFS share path via https://github.com/gondor/docker-volume-netshare.

I think that with this plethora of use-cases from Windows support to volumes with custom drivers -  escaping is the only reasonable solution.

**Comment by nbastin** [comment]
+1 they should be able to be escaped.  Colons in linux paths are completely legal and it's unreasonable that there is no way to map these into containers.

**Comment by RobertAtomic** [comment]
I notice that Docker for Windows has no problem with colons in the file path.  Will Docker also gain this ability soon?

**Comment by shnhrrsn** [comment]
For anyone else who ends up here via Google, this is now possible via `--mount`:

```bash
docker run --mount type=bind,source=/path/with:colon,destination=/mnt
```

**Comment by thaJeztah** [comment]
Ah, yes, the `--mount` flag was added to address this issue (i.e., the shorthand `-v <src>:<dest>` format being ambiguous). This flag was added in this PR; https://github.com/moby/moby/pull/32251, and included in docker 17.05 and up. Also see the discussion on https://github.com/moby/moby/issues/28527

I'm closing this issue, because this problem is addressed, but feel free to comment after that

**Comment by mercuriev** [comment]
`mount` doesn't solve same problem with `--device`.
I am unable to attach device with colons to container.
Ex: `/dev/serial/by-path/platform-3f980000.usb-usb-0:1.2.1:1.0-port0`

**Comment by atline** [comment]
> `mount` doesn't solve same problem with `--device`.
> I am unable to attach device with colons to container.
> Ex: `/dev/serial/by-path/platform-3f980000.usb-usb-0:1.2.1:1.0-port0`

Any one handle this?

**Comment by atline** [comment]
> `mount` doesn't solve same problem with `--device`.
> I am unable to attach device with colons to container.
> Ex: `/dev/serial/by-path/platform-3f980000.usb-usb-0:1.2.1:1.0-port0`

No one handle this?

**Comment by mercuriev** [comment]
Symlink to required device helps.

**Comment by cpuguy83** [comment]
We could probably add a special type for device to the `--mount` syntax. Then you just can't have a `,` in the device name.

**Comment by cpuguy83** [comment]
And by "we" I mean I think such a patch would be acceptable.

**Comment by KevOrr** [comment]
From what I can tell, `-v` doesn't accept paths that contain colons, and `--mount` doesn't accept paths that contain commas. Is there any way to pass an __arbitrary__ path to docker and just expect it to work without e.g. symlinking beforehand?

**Comment by cpuguy83** [comment]
@KevOrr I'm not sure, but I think the CLI should support escaping the commas.

**Comment by charmander** [comment]
@KevOrr It’s a CSV row (really). If you quote it and replace `"` with `""`, it should be safe.

**Comment by KevOrr** [comment]
@cpuguy83 @charmander  Thank you very much, that worked.

```bash
$ touch 'hi,bye:"quote"'
$ docker run --rm --mount "type=bind,\"source=$PWD/hi,bye:\"\"quote\"\"\",destination=/tmp/hi" -it bash
bash-5.0# ls -al /tmp
total 8
drwxrwxrwt    1 root     root          4096 Jun 25 13:43 .
drwxr-xr-x    1 root     root          4096 Jun 25 13:43 ..
-rw-r--r--    1 1000     1000             0 Jun 25 13:42 hi
```
